#include <stdio.h>
#include "instr_lists.h"
#include "opcodes.h"
#include "prefixed_opcodes.h"

void initialize_length_table(s_emu *emu)
{
    memset(&emu->length_table, 1, OPCODE_NB);
    
    emu->length_table[0x01] = 3;
    emu->length_table[0x06] = 2;
    emu->length_table[0x08] = 3;
    emu->length_table[0x0E] = 2;
    emu->length_table[0x11] = 3;
    //emu->length_table[0x15] = 1;
    emu->length_table[0x16] = 2;
    emu->length_table[0x18] = 2;
    emu->length_table[0x1E] = 2;
    emu->length_table[0x20] = 2;
    emu->length_table[0x21] = 3;
    emu->length_table[0x26] = 2;
    emu->length_table[0x28] = 2;
    emu->length_table[0x2E] = 2;
    emu->length_table[0x30] = 2;
    emu->length_table[0x31] = 3;
    emu->length_table[0x36] = 2;
    emu->length_table[0x38] = 2;
    emu->length_table[0x3e] = 2;
    emu->length_table[0x76] = 0; //HALT
    emu->length_table[0xc2] = 3;
    emu->length_table[0xc3] = 3;
    emu->length_table[0xc4] = 3;
    emu->length_table[0xc6] = 2;
    emu->length_table[0xca] = 3;
    emu->length_table[0xcb] = 2;
    emu->length_table[0xcc] = 3;
    emu->length_table[0xcd] = 3;
    emu->length_table[0xce] = 2;
    emu->length_table[0xd2] = 3;
    emu->length_table[0xd3] = 0;
    emu->length_table[0xd4] = 3;
    emu->length_table[0xd6] = 2;
    emu->length_table[0xda] = 3;
    emu->length_table[0xdb] = 0;
    emu->length_table[0xdc] = 3;
    emu->length_table[0xdd] = 0;
    emu->length_table[0xde] = 2;
    emu->length_table[0xe0] = 2;
    emu->length_table[0xe3] = 0;
    emu->length_table[0xe4] = 0;
    emu->length_table[0xe6] = 2;
    emu->length_table[0xe8] = 2;
    emu->length_table[0xea] = 3;
    emu->length_table[0xeb] = 0;
    emu->length_table[0xec] = 0;
    emu->length_table[0xed] = 0;
    emu->length_table[0xee] = 2;
    emu->length_table[0xf0] = 2;
    emu->length_table[0xf4] = 0;
    emu->length_table[0xf6] = 2;
    emu->length_table[0xf8] = 2;
    emu->length_table[0xfa] = 3;
    emu->length_table[0xfc] = 0;
    emu->length_table[0xfd] = 0;
    emu->length_table[0xfe] = 2;
}

void init_timing_table(s_emu *emu)
{
    memset(emu->timing_table, 0, sizeof(uint8_t[2][OPCODE_NB]));
    emu->timing_table[0][0x00] = 4;
    emu->timing_table[0][0x01] = 12;
    emu->timing_table[0][0x02] = 8;
    emu->timing_table[0][0x03] = 8;
    emu->timing_table[0][0x04] = 4;
    emu->timing_table[0][0x05] = 4;
    emu->timing_table[0][0x06] = 8;
    emu->timing_table[0][0x07] = 4;
    emu->timing_table[0][0x08] = 20;
    emu->timing_table[0][0x09] = 8;
    emu->timing_table[0][0x0A] = 8;
    emu->timing_table[0][0x0B] = 8;
    emu->timing_table[0][0x0C] = 4;
    emu->timing_table[0][0x0D] = 4;
    emu->timing_table[0][0x0E] = 8;
    emu->timing_table[0][0x0F] = 4;
    emu->timing_table[0][0x10] = 4;
    emu->timing_table[0][0x11] = 12;
    emu->timing_table[0][0x12] = 8;
    emu->timing_table[0][0x13] = 8;
    emu->timing_table[0][0x14] = 4;
    emu->timing_table[0][0x15] = 4;
    emu->timing_table[0][0x16] = 8;
    emu->timing_table[0][0x17] = 4;
    emu->timing_table[0][0x18] = 12;
    emu->timing_table[0][0x19] = 8;
    emu->timing_table[0][0x1A] = 8;
    emu->timing_table[0][0x1B] = 8;
    emu->timing_table[0][0x1C] = 4;
    emu->timing_table[0][0x1D] = 4;
    emu->timing_table[0][0x1E] = 8;
    emu->timing_table[0][0x1F] = 4;
    emu->timing_table[0][0x20] = 12;
    emu->timing_table[1][0x20] = 8;
    emu->timing_table[0][0x21] = 12;
    emu->timing_table[0][0x22] = 8;
    emu->timing_table[0][0x23] = 8;
    emu->timing_table[0][0x24] = 4;
    emu->timing_table[0][0x25] = 4;
    emu->timing_table[0][0x26] = 8;
    emu->timing_table[0][0x27] = 4;
    emu->timing_table[0][0x28] = 12;
    emu->timing_table[1][0x28] = 8;
    emu->timing_table[0][0x29] = 8;
    emu->timing_table[0][0x2A] = 8;
    emu->timing_table[0][0x2B] = 8;
    emu->timing_table[0][0x2C] = 4;
    emu->timing_table[0][0x2D] = 4;
    emu->timing_table[0][0x2E] = 8;
    emu->timing_table[0][0x2F] = 4;
    emu->timing_table[0][0x30] = 12;
    emu->timing_table[1][0x30] = 8;
    emu->timing_table[0][0x31] = 12;
    emu->timing_table[0][0x32] = 8;
    emu->timing_table[0][0x33] = 8;
    emu->timing_table[0][0x34] = 12;
    emu->timing_table[0][0x35] = 12;
    emu->timing_table[0][0x36] = 12;
    emu->timing_table[0][0x37] = 4;
    emu->timing_table[0][0x38] = 12;
    emu->timing_table[1][0x38] = 8;
    emu->timing_table[0][0x39] = 8;
    emu->timing_table[0][0x3A] = 8;
    emu->timing_table[0][0x3B] = 8;
    emu->timing_table[0][0x3C] = 4;
    emu->timing_table[0][0x3D] = 4;
    emu->timing_table[0][0x3E] = 8;
    emu->timing_table[0][0x3F] = 4;
    emu->timing_table[0][0x40] = 4;
    emu->timing_table[0][0x41] = 4;
    emu->timing_table[0][0x42] = 4;
    emu->timing_table[0][0x43] = 4;
    emu->timing_table[0][0x44] = 4;
    emu->timing_table[0][0x45] = 4;
    emu->timing_table[0][0x46] = 8;
    emu->timing_table[0][0x47] = 4;
    emu->timing_table[0][0x48] = 4;
    emu->timing_table[0][0x49] = 4;
    emu->timing_table[0][0x4A] = 4;
    emu->timing_table[0][0x4B] = 4;
    emu->timing_table[0][0x4C] = 4;
    emu->timing_table[0][0x4D] = 4;
    emu->timing_table[0][0x4E] = 8;
    emu->timing_table[0][0x4F] = 4;
    emu->timing_table[0][0x50] = 4;
    emu->timing_table[0][0x51] = 4;
    emu->timing_table[0][0x52] = 4;
    emu->timing_table[0][0x53] = 4;
    emu->timing_table[0][0x54] = 4;
    emu->timing_table[0][0x55] = 4;
    emu->timing_table[0][0x56] = 8;
    emu->timing_table[0][0x57] = 4;
    emu->timing_table[0][0x58] = 4;
    emu->timing_table[0][0x59] = 4;
    emu->timing_table[0][0x5A] = 4;
    emu->timing_table[0][0x5B] = 4;
    emu->timing_table[0][0x5C] = 4;
    emu->timing_table[0][0x5D] = 4;
    emu->timing_table[0][0x5E] = 8;
    emu->timing_table[0][0x5F] = 4;
    emu->timing_table[0][0x60] = 4;
    emu->timing_table[0][0x61] = 4;
    emu->timing_table[0][0x62] = 4;
    emu->timing_table[0][0x63] = 4;
    emu->timing_table[0][0x64] = 4;
    emu->timing_table[0][0x65] = 4;
    emu->timing_table[0][0x66] = 8;
    emu->timing_table[0][0x67] = 4;
    emu->timing_table[0][0x68] = 4;
    emu->timing_table[0][0x69] = 4;
    emu->timing_table[0][0x6A] = 4;
    emu->timing_table[0][0x6B] = 4;
    emu->timing_table[0][0x6C] = 4;
    emu->timing_table[0][0x6D] = 4;
    emu->timing_table[0][0x6E] = 8;
    emu->timing_table[0][0x6F] = 4;
    emu->timing_table[0][0x70] = 8;
    emu->timing_table[0][0x71] = 8;
    emu->timing_table[0][0x72] = 8;
    emu->timing_table[0][0x73] = 8;
    emu->timing_table[0][0x74] = 8;
    emu->timing_table[0][0x75] = 8;
    emu->timing_table[0][0x76] = 4;
    emu->timing_table[0][0x77] = 8;
    emu->timing_table[0][0x78] = 4;
    emu->timing_table[0][0x79] = 4;
    emu->timing_table[0][0x7A] = 4;
    emu->timing_table[0][0x7B] = 4;
    emu->timing_table[0][0x7C] = 4;
    emu->timing_table[0][0x7D] = 4;
    emu->timing_table[0][0x7E] = 8;
    emu->timing_table[0][0x7F] = 4;
    emu->timing_table[0][0x80] = 4;
    emu->timing_table[0][0x81] = 4;
    emu->timing_table[0][0x82] = 4;
    emu->timing_table[0][0x83] = 4;
    emu->timing_table[0][0x84] = 4;
    emu->timing_table[0][0x85] = 4;
    emu->timing_table[0][0x86] = 8;
    emu->timing_table[0][0x87] = 4;
    emu->timing_table[0][0x88] = 4;
    emu->timing_table[0][0x89] = 4;
    emu->timing_table[0][0x8A] = 4;
    emu->timing_table[0][0x8B] = 4;
    emu->timing_table[0][0x8C] = 4;
    emu->timing_table[0][0x8D] = 4;
    emu->timing_table[0][0x8E] = 8;
    emu->timing_table[0][0x8F] = 4;
    emu->timing_table[0][0x90] = 4;
    emu->timing_table[0][0x91] = 4;
    emu->timing_table[0][0x92] = 4;
    emu->timing_table[0][0x93] = 4;
    emu->timing_table[0][0x94] = 4;
    emu->timing_table[0][0x95] = 4;
    emu->timing_table[0][0x96] = 8;
    emu->timing_table[0][0x97] = 4;
    emu->timing_table[0][0x98] = 4;
    emu->timing_table[0][0x99] = 4;
    emu->timing_table[0][0x9A] = 4;
    emu->timing_table[0][0x9B] = 4;
    emu->timing_table[0][0x9C] = 4;
    emu->timing_table[0][0x9D] = 4;
    emu->timing_table[0][0x9E] = 8;
    emu->timing_table[0][0x9F] = 4;
    emu->timing_table[0][0xA0] = 4;
    emu->timing_table[0][0xA1] = 4;
    emu->timing_table[0][0xA2] = 4;
    emu->timing_table[0][0xA3] = 4;
    emu->timing_table[0][0xA4] = 4;
    emu->timing_table[0][0xA5] = 4;
    emu->timing_table[0][0xA6] = 8;
    emu->timing_table[0][0xA7] = 4;
    emu->timing_table[0][0xA8] = 4;
    emu->timing_table[0][0xA9] = 4;
    emu->timing_table[0][0xAA] = 4;
    emu->timing_table[0][0xAB] = 4;
    emu->timing_table[0][0xAC] = 4;
    emu->timing_table[0][0xAD] = 4;
    emu->timing_table[0][0xAE] = 8;
    emu->timing_table[0][0xAF] = 4;
    emu->timing_table[0][0xB0] = 4;
    emu->timing_table[0][0xB1] = 4;
    emu->timing_table[0][0xB2] = 4;
    emu->timing_table[0][0xB3] = 4;
    emu->timing_table[0][0xB4] = 4;
    emu->timing_table[0][0xB5] = 4;
    emu->timing_table[0][0xB6] = 8;
    emu->timing_table[0][0xB7] = 4;
    emu->timing_table[0][0xB8] = 4;
    emu->timing_table[0][0xB9] = 4;
    emu->timing_table[0][0xBA] = 4;
    emu->timing_table[0][0xBB] = 4;
    emu->timing_table[0][0xBC] = 4;
    emu->timing_table[0][0xBD] = 4;
    emu->timing_table[0][0xBE] = 8;
    emu->timing_table[0][0xBF] = 4;
    emu->timing_table[0][0xC0] = 20;
    emu->timing_table[1][0xC0] = 8;
    emu->timing_table[0][0xC1] = 12;
    emu->timing_table[0][0xC2] = 16;
    emu->timing_table[1][0xC2] = 12;
    emu->timing_table[0][0xC3] = 16;
    emu->timing_table[0][0xC4] = 24;
    emu->timing_table[1][0xC4] = 12;
    emu->timing_table[0][0xC5] = 16;
    emu->timing_table[0][0xC6] = 8;
    emu->timing_table[0][0xC7] = 16;
    emu->timing_table[0][0xC8] = 20;
    emu->timing_table[1][0xC8] = 8;
    emu->timing_table[0][0xC9] = 16;
    emu->timing_table[0][0xCA] = 16;
    emu->timing_table[1][0xCA] = 12;
    //emu->timing_table[0][0xCB] = 4;
    emu->timing_table[0][0xCC] = 24;
    emu->timing_table[1][0xCC] = 12;
    emu->timing_table[0][0xCD] = 24;
    emu->timing_table[0][0xCE] = 8;
    emu->timing_table[0][0xCF] = 16;
    emu->timing_table[0][0xD0] = 20;
    emu->timing_table[1][0xD0] = 8;
    emu->timing_table[0][0xD1] = 12;
    emu->timing_table[0][0xD2] = 16;
    emu->timing_table[1][0xD2] = 12;
    emu->timing_table[0][0xD4] = 24;
    emu->timing_table[1][0xD4] = 12;
    emu->timing_table[0][0xD5] = 16;
    emu->timing_table[0][0xD6] = 8;
    emu->timing_table[0][0xD7] = 16;
    emu->timing_table[0][0xD8] = 20;
    emu->timing_table[1][0xD8] = 8;
    emu->timing_table[0][0xD9] = 16;
    emu->timing_table[0][0xDA] = 16;
    emu->timing_table[1][0xDA] = 12;
    emu->timing_table[0][0xDC] = 24;
    emu->timing_table[1][0xDC] = 12;
    emu->timing_table[0][0xDE] = 8;
    emu->timing_table[0][0xDF] = 16;
    emu->timing_table[0][0xE0] = 12;
    emu->timing_table[0][0xE1] = 12;
    emu->timing_table[0][0xE2] = 8;
    emu->timing_table[0][0xE5] = 16;
    emu->timing_table[0][0xE6] = 8;
    emu->timing_table[0][0xE7] = 16;
    emu->timing_table[0][0xE8] = 16;
    emu->timing_table[0][0xE9] = 4;
    emu->timing_table[0][0xEA] = 16;
    emu->timing_table[0][0xEE] = 8;
    emu->timing_table[0][0xEF] = 16;
    emu->timing_table[0][0xF0] = 12;
    emu->timing_table[0][0xF1] = 12;
    emu->timing_table[0][0xF2] = 8;
    emu->timing_table[0][0xF3] = 4;
    emu->timing_table[0][0xF5] = 16;
    emu->timing_table[0][0xF6] = 8;
    emu->timing_table[0][0xF7] = 16;
    emu->timing_table[0][0xF8] = 12;
    emu->timing_table[0][0xF9] = 8;
    emu->timing_table[0][0xFA] = 16;
    emu->timing_table[0][0xFB] = 4;
    emu->timing_table[0][0xFE] = 8;
    emu->timing_table[0][0xFF] = 16;
}

void init_prefix_timing_table(s_emu *emu)
{
    memset(emu->prefix_timing_table, 0, sizeof(emu->prefix_timing_table));
    emu->prefix_timing_table[0x00] = 8;
    emu->prefix_timing_table[0x01] = 8;
    emu->prefix_timing_table[0x02] = 8;
    emu->prefix_timing_table[0x03] = 8;
    emu->prefix_timing_table[0x04] = 8;
    emu->prefix_timing_table[0x05] = 8;
    emu->prefix_timing_table[0x06] = 16;
    emu->prefix_timing_table[0x07] = 8;
    emu->prefix_timing_table[0x08] = 8;
    emu->prefix_timing_table[0x09] = 8;
    emu->prefix_timing_table[0x0A] = 8;
    emu->prefix_timing_table[0x0B] = 8;
    emu->prefix_timing_table[0x0C] = 8;
    emu->prefix_timing_table[0x0D] = 8;
    emu->prefix_timing_table[0x0E] = 16;
    emu->prefix_timing_table[0x0F] = 8;
    emu->prefix_timing_table[0x10] = 8;
    emu->prefix_timing_table[0x11] = 8;
    emu->prefix_timing_table[0x12] = 8;
    emu->prefix_timing_table[0x13] = 8;
    emu->prefix_timing_table[0x14] = 8;
    emu->prefix_timing_table[0x15] = 8;
    emu->prefix_timing_table[0x16] = 16;
    emu->prefix_timing_table[0x17] = 8;
    emu->prefix_timing_table[0x18] = 8;
    emu->prefix_timing_table[0x19] = 8;
    emu->prefix_timing_table[0x1A] = 8;
    emu->prefix_timing_table[0x1B] = 8;
    emu->prefix_timing_table[0x1C] = 8;
    emu->prefix_timing_table[0x1D] = 8;
    emu->prefix_timing_table[0x1E] = 16;
    emu->prefix_timing_table[0x1F] = 8;
    emu->prefix_timing_table[0x20] = 8;
    emu->prefix_timing_table[0x21] = 8;
    emu->prefix_timing_table[0x22] = 8;
    emu->prefix_timing_table[0x23] = 8;
    emu->prefix_timing_table[0x24] = 8;
    emu->prefix_timing_table[0x25] = 8;
    emu->prefix_timing_table[0x26] = 16;
    emu->prefix_timing_table[0x27] = 8;
    emu->prefix_timing_table[0x28] = 8;
    emu->prefix_timing_table[0x29] = 8;
    emu->prefix_timing_table[0x2A] = 8;
    emu->prefix_timing_table[0x2B] = 8;
    emu->prefix_timing_table[0x2C] = 8;
    emu->prefix_timing_table[0x2D] = 8;
    emu->prefix_timing_table[0x2E] = 16;
    emu->prefix_timing_table[0x2F] = 8;
    emu->prefix_timing_table[0x30] = 8;
    emu->prefix_timing_table[0x31] = 8;
    emu->prefix_timing_table[0x32] = 8;
    emu->prefix_timing_table[0x33] = 8;
    emu->prefix_timing_table[0x34] = 8;
    emu->prefix_timing_table[0x35] = 8;
    emu->prefix_timing_table[0x36] = 16;
    emu->prefix_timing_table[0x37] = 8;
    emu->prefix_timing_table[0x38] = 8;
    emu->prefix_timing_table[0x39] = 8;
    emu->prefix_timing_table[0x3A] = 8;
    emu->prefix_timing_table[0x3B] = 8;
    emu->prefix_timing_table[0x3C] = 8;
    emu->prefix_timing_table[0x3D] = 8;
    emu->prefix_timing_table[0x3E] = 16;
    emu->prefix_timing_table[0x3F] = 8;
    emu->prefix_timing_table[0x40] = 8;
    emu->prefix_timing_table[0x41] = 8;
    emu->prefix_timing_table[0x42] = 8;
    emu->prefix_timing_table[0x43] = 8;
    emu->prefix_timing_table[0x44] = 8;
    emu->prefix_timing_table[0x45] = 8;
    emu->prefix_timing_table[0x46] = 16;
    emu->prefix_timing_table[0x47] = 8;
    emu->prefix_timing_table[0x48] = 8;
    emu->prefix_timing_table[0x49] = 8;
    emu->prefix_timing_table[0x4A] = 8;
    emu->prefix_timing_table[0x4B] = 8;
    emu->prefix_timing_table[0x4C] = 8;
    emu->prefix_timing_table[0x4D] = 8;
    emu->prefix_timing_table[0x4E] = 16;
    emu->prefix_timing_table[0x4F] = 8;
    emu->prefix_timing_table[0x50] = 8;
    emu->prefix_timing_table[0x51] = 8;
    emu->prefix_timing_table[0x52] = 8;
    emu->prefix_timing_table[0x53] = 8;
    emu->prefix_timing_table[0x54] = 8;
    emu->prefix_timing_table[0x55] = 8;
    emu->prefix_timing_table[0x56] = 16;
    emu->prefix_timing_table[0x57] = 8;
    emu->prefix_timing_table[0x58] = 8;
    emu->prefix_timing_table[0x59] = 8;
    emu->prefix_timing_table[0x5A] = 8;
    emu->prefix_timing_table[0x5B] = 8;
    emu->prefix_timing_table[0x5C] = 8;
    emu->prefix_timing_table[0x5D] = 8;
    emu->prefix_timing_table[0x5E] = 16;
    emu->prefix_timing_table[0x5F] = 8;
    emu->prefix_timing_table[0x60] = 8;
    emu->prefix_timing_table[0x61] = 8;
    emu->prefix_timing_table[0x62] = 8;
    emu->prefix_timing_table[0x63] = 8;
    emu->prefix_timing_table[0x64] = 8;
    emu->prefix_timing_table[0x65] = 8;
    emu->prefix_timing_table[0x66] = 16;
    emu->prefix_timing_table[0x67] = 8;
    emu->prefix_timing_table[0x68] = 8;
    emu->prefix_timing_table[0x69] = 8;
    emu->prefix_timing_table[0x6A] = 8;
    emu->prefix_timing_table[0x6B] = 8;
    emu->prefix_timing_table[0x6C] = 8;
    emu->prefix_timing_table[0x6D] = 8;
    emu->prefix_timing_table[0x6E] = 16;
    emu->prefix_timing_table[0x6F] = 8;
    emu->prefix_timing_table[0x70] = 8;
    emu->prefix_timing_table[0x71] = 8;
    emu->prefix_timing_table[0x72] = 8;
    emu->prefix_timing_table[0x73] = 8;
    emu->prefix_timing_table[0x74] = 8;
    emu->prefix_timing_table[0x75] = 8;
    emu->prefix_timing_table[0x76] = 16;
    emu->prefix_timing_table[0x77] = 8;
    emu->prefix_timing_table[0x78] = 8;
    emu->prefix_timing_table[0x79] = 8;
    emu->prefix_timing_table[0x7A] = 8;
    emu->prefix_timing_table[0x7B] = 8;
    emu->prefix_timing_table[0x7C] = 8;
    emu->prefix_timing_table[0x7D] = 8;
    emu->prefix_timing_table[0x7E] = 16;
    emu->prefix_timing_table[0x7F] = 8;
    emu->prefix_timing_table[0x80] = 8;
    emu->prefix_timing_table[0x81] = 8;
    emu->prefix_timing_table[0x82] = 8;
    emu->prefix_timing_table[0x83] = 8;
    emu->prefix_timing_table[0x84] = 8;
    emu->prefix_timing_table[0x85] = 8;
    emu->prefix_timing_table[0x86] = 16;
    emu->prefix_timing_table[0x87] = 8;
    emu->prefix_timing_table[0x88] = 8;
    emu->prefix_timing_table[0x89] = 8;
    emu->prefix_timing_table[0x8A] = 8;
    emu->prefix_timing_table[0x8B] = 8;
    emu->prefix_timing_table[0x8C] = 8;
    emu->prefix_timing_table[0x8D] = 8;
    emu->prefix_timing_table[0x8E] = 16;
    emu->prefix_timing_table[0x8F] = 8;
    emu->prefix_timing_table[0x90] = 8;
    emu->prefix_timing_table[0x91] = 8;
    emu->prefix_timing_table[0x92] = 8;
    emu->prefix_timing_table[0x93] = 8;
    emu->prefix_timing_table[0x94] = 8;
    emu->prefix_timing_table[0x95] = 8;
    emu->prefix_timing_table[0x96] = 16;
    emu->prefix_timing_table[0x97] = 8;
    emu->prefix_timing_table[0x98] = 8;
    emu->prefix_timing_table[0x99] = 8;
    emu->prefix_timing_table[0x9A] = 8;
    emu->prefix_timing_table[0x9B] = 8;
    emu->prefix_timing_table[0x9C] = 8;
    emu->prefix_timing_table[0x9D] = 8;
    emu->prefix_timing_table[0x9E] = 16;
    emu->prefix_timing_table[0x9F] = 8;
    emu->prefix_timing_table[0xA0] = 8;
    emu->prefix_timing_table[0xA1] = 8;
    emu->prefix_timing_table[0xA2] = 8;
    emu->prefix_timing_table[0xA3] = 8;
    emu->prefix_timing_table[0xA4] = 8;
    emu->prefix_timing_table[0xA5] = 8;
    emu->prefix_timing_table[0xA6] = 16;
    emu->prefix_timing_table[0xA7] = 8;
    emu->prefix_timing_table[0xA8] = 8;
    emu->prefix_timing_table[0xA9] = 8;
    emu->prefix_timing_table[0xAA] = 8;
    emu->prefix_timing_table[0xAB] = 8;
    emu->prefix_timing_table[0xAC] = 8;
    emu->prefix_timing_table[0xAD] = 8;
    emu->prefix_timing_table[0xAE] = 16;
    emu->prefix_timing_table[0xAF] = 8;
    emu->prefix_timing_table[0xB0] = 8;
    emu->prefix_timing_table[0xB1] = 8;
    emu->prefix_timing_table[0xB2] = 8;
    emu->prefix_timing_table[0xB3] = 8;
    emu->prefix_timing_table[0xB4] = 8;
    emu->prefix_timing_table[0xB5] = 8;
    emu->prefix_timing_table[0xB6] = 16;
    emu->prefix_timing_table[0xB7] = 8;
    emu->prefix_timing_table[0xB8] = 8;
    emu->prefix_timing_table[0xB9] = 8;
    emu->prefix_timing_table[0xBA] = 8;
    emu->prefix_timing_table[0xBB] = 8;
    emu->prefix_timing_table[0xBC] = 8;
    emu->prefix_timing_table[0xBD] = 8;
    emu->prefix_timing_table[0xBE] = 16;
    emu->prefix_timing_table[0xBF] = 8;
    emu->prefix_timing_table[0xC0] = 8;
    emu->prefix_timing_table[0xC1] = 8;
    emu->prefix_timing_table[0xC2] = 8;
    emu->prefix_timing_table[0xC3] = 8;
    emu->prefix_timing_table[0xC4] = 8;
    emu->prefix_timing_table[0xC5] = 8;
    emu->prefix_timing_table[0xC6] = 16;
    emu->prefix_timing_table[0xC7] = 8;
    emu->prefix_timing_table[0xC8] = 8;
    emu->prefix_timing_table[0xC9] = 8;
    emu->prefix_timing_table[0xCA] = 8;
    emu->prefix_timing_table[0xCB] = 8;
    emu->prefix_timing_table[0xCC] = 8;
    emu->prefix_timing_table[0xCD] = 8;
    emu->prefix_timing_table[0xCE] = 16;
    emu->prefix_timing_table[0xCF] = 8;
    emu->prefix_timing_table[0xD0] = 8;
    emu->prefix_timing_table[0xD1] = 8;
    emu->prefix_timing_table[0xD2] = 8;
    emu->prefix_timing_table[0xD3] = 8;
    emu->prefix_timing_table[0xD4] = 8;
    emu->prefix_timing_table[0xD5] = 8;
    emu->prefix_timing_table[0xD6] = 16;
    emu->prefix_timing_table[0xD7] = 8;
    emu->prefix_timing_table[0xD8] = 8;
    emu->prefix_timing_table[0xD9] = 8;
    emu->prefix_timing_table[0xDA] = 8;
    emu->prefix_timing_table[0xDB] = 8;
    emu->prefix_timing_table[0xDC] = 8;
    emu->prefix_timing_table[0xDD] = 8;
    emu->prefix_timing_table[0xDE] = 16;
    emu->prefix_timing_table[0xDF] = 8;
    emu->prefix_timing_table[0xE0] = 8;
    emu->prefix_timing_table[0xE1] = 8;
    emu->prefix_timing_table[0xE2] = 8;
    emu->prefix_timing_table[0xE3] = 8;
    emu->prefix_timing_table[0xE4] = 8;
    emu->prefix_timing_table[0xE5] = 8;
    emu->prefix_timing_table[0xE6] = 16;
    emu->prefix_timing_table[0xE7] = 8;
    emu->prefix_timing_table[0xE8] = 8;
    emu->prefix_timing_table[0xE9] = 8;
    emu->prefix_timing_table[0xEA] = 8;
    emu->prefix_timing_table[0xEB] = 8;
    emu->prefix_timing_table[0xEC] = 8;
    emu->prefix_timing_table[0xED] = 8;
    emu->prefix_timing_table[0xEE] = 16;
    emu->prefix_timing_table[0xEF] = 8;
    emu->prefix_timing_table[0xF0] = 8;
    emu->prefix_timing_table[0xF1] = 8;
    emu->prefix_timing_table[0xF2] = 8;
    emu->prefix_timing_table[0xF3] = 8;
    emu->prefix_timing_table[0xF4] = 8;
    emu->prefix_timing_table[0xF5] = 8;
    emu->prefix_timing_table[0xF6] = 16;
    emu->prefix_timing_table[0xF7] = 8;
    emu->prefix_timing_table[0xF8] = 8;
    emu->prefix_timing_table[0xF9] = 8;
    emu->prefix_timing_table[0xFA] = 8;
    emu->prefix_timing_table[0xFB] = 8;
    emu->prefix_timing_table[0xFC] = 8;
    emu->prefix_timing_table[0xFD] = 8;
    emu->prefix_timing_table[0xFE] = 16;
    emu->prefix_timing_table[0xFF] = 8;
}

void init_opcodes_pointers(void (*opcode_functions[OPCODE_NB])(void *, uint32_t))
{
    opcode_functions[0x00] = &NOP;
    opcode_functions[0x01] = &LD_BC_d16;
    opcode_functions[0x02] = &LD_derefBC_A;
    opcode_functions[0x03] = &INC_BC;
    opcode_functions[0x04] = &INC_B;
    opcode_functions[0x05] = &DEC_B;
    opcode_functions[0x06] = &LD_B_d8;
    opcode_functions[0x07] = &RLCA;
    opcode_functions[0x08] = &LD_derefa16_SP;
    opcode_functions[0x09] = &ADD_HL_BC;
    opcode_functions[0x0A] = &LD_A_derefBC;
    opcode_functions[0x0B] = &DEC_BC;
    opcode_functions[0x0C] = &INC_C;
    opcode_functions[0x0D] = &DEC_C;
    opcode_functions[0x0E] = &LD_C_d8;
    opcode_functions[0x0F] = &RRCA;
    opcode_functions[0x10] = &STOP_0;
    opcode_functions[0x11] = &LD_DE_d16;
    opcode_functions[0x12] = &LD_derefDE_A;
    opcode_functions[0x13] = &INC_DE;
    opcode_functions[0x14] = &INC_D;
    opcode_functions[0x15] = &DEC_D;
    opcode_functions[0x16] = &LD_D_d8;
    opcode_functions[0x17] = &RLA;
    opcode_functions[0x18] = &JR_r8;
    opcode_functions[0x19] = &ADD_HL_DE;
    opcode_functions[0x1A] = &LD_A_derefDE;
    opcode_functions[0x1B] = &DEC_DE;
    opcode_functions[0x1C] = &INC_E;
    opcode_functions[0x1D] = &DEC_E;
    opcode_functions[0x1E] = &LD_E_d8;
    opcode_functions[0x1F] = &RRA;
    opcode_functions[0x20] = &JR_NZ_r8;
    opcode_functions[0x21] = &LD_HL_d16;
    opcode_functions[0x22] = &LD_derefHLplus_A;
    opcode_functions[0x23] = &INC_HL;
    opcode_functions[0x24] = &INC_H;
    opcode_functions[0x25] = &DEC_H;
    opcode_functions[0x26] = &LD_H_d8;
    opcode_functions[0x27] = &DAA;
    opcode_functions[0x28] = &JR_Z_r8;
    opcode_functions[0x29] = &ADD_HL_HL;
    opcode_functions[0x2A] = &LD_A_derefHLplus;
    opcode_functions[0x2B] = &DEC_HL;
    opcode_functions[0x2C] = &INC_L;
    opcode_functions[0x2D] = &DEC_L;
    opcode_functions[0x2E] = &LD_L_d8;
    opcode_functions[0x2F] = &CPL;
    opcode_functions[0x30] = &JR_NC_r8;
    opcode_functions[0x31] = &LD_SP_d16;
    opcode_functions[0x32] = &LD_derefHLminus_A;
    opcode_functions[0x33] = &INC_SP;
    opcode_functions[0x34] = &INC_derefHL;
    opcode_functions[0x35] = &DEC_derefHL;
    opcode_functions[0x36] = &LD_derefHL_d8;
    opcode_functions[0x37] = &SCF;
    opcode_functions[0x38] = &JR_C_r8;
    opcode_functions[0x39] = &ADD_HL_SP;
    opcode_functions[0x3A] = &LD_A_derefHLminus;
    opcode_functions[0x3B] = &DEC_SP;
    opcode_functions[0x3C] = &INC_A;
    opcode_functions[0x3D] = &DEC_A;
    opcode_functions[0x3E] = &LD_A_d8;
    opcode_functions[0x3F] = &CCF;
    opcode_functions[0x40] = &LD_B_B;
    opcode_functions[0x41] = &LD_B_C;
    opcode_functions[0x42] = &LD_B_D;
    opcode_functions[0x43] = &LD_B_E;
    opcode_functions[0x44] = &LD_B_H;
    opcode_functions[0x45] = &LD_B_L;
    opcode_functions[0x46] = &LD_B_derefHL;
    opcode_functions[0x47] = &LD_B_A;
    opcode_functions[0x48] = &LD_C_B;
    opcode_functions[0x49] = &LD_C_C;
    opcode_functions[0x4A] = &LD_C_D;
    opcode_functions[0x4B] = &LD_C_E;
    opcode_functions[0x4C] = &LD_C_H;
    opcode_functions[0x4D] = &LD_C_L;
    opcode_functions[0x4E] = &LD_C_derefHL;
    opcode_functions[0x4F] = &LD_C_A;
    opcode_functions[0x50] = &LD_D_B;
    opcode_functions[0x51] = &LD_D_C;
    opcode_functions[0x52] = &LD_D_D;
    opcode_functions[0x53] = &LD_D_E;
    opcode_functions[0x54] = &LD_D_H;
    opcode_functions[0x55] = &LD_D_L;
    opcode_functions[0x56] = &LD_D_derefHL;
    opcode_functions[0x57] = &LD_D_A;
    opcode_functions[0x58] = &LD_E_B;
    opcode_functions[0x59] = &LD_E_C;
    opcode_functions[0x5A] = &LD_E_D;
    opcode_functions[0x5B] = &LD_E_E;
    opcode_functions[0x5C] = &LD_E_H;
    opcode_functions[0x5D] = &LD_E_L;
    opcode_functions[0x5E] = &LD_E_derefHL;
    opcode_functions[0x5F] = &LD_E_A;
    opcode_functions[0x60] = &LD_H_B;
    opcode_functions[0x61] = &LD_H_C;
    opcode_functions[0x62] = &LD_H_D;
    opcode_functions[0x63] = &LD_H_E;
    opcode_functions[0x64] = &LD_H_H;
    opcode_functions[0x65] = &LD_H_L;
    opcode_functions[0x66] = &LD_H_derefHL;
    opcode_functions[0x67] = &LD_H_A;
    opcode_functions[0x68] = &LD_L_B;
    opcode_functions[0x69] = &LD_L_C;
    opcode_functions[0x6A] = &LD_L_D;
    opcode_functions[0x6B] = &LD_L_E;
    opcode_functions[0x6C] = &LD_L_H;
    opcode_functions[0x6D] = &LD_L_L;
    opcode_functions[0x6E] = &LD_L_derefHL;
    opcode_functions[0x6F] = &LD_L_A;
    opcode_functions[0x70] = &LD_derefHL_B;
    opcode_functions[0x71] = &LD_derefHL_C;
    opcode_functions[0x72] = &LD_derefHL_D;
    opcode_functions[0x73] = &LD_derefHL_E;
    opcode_functions[0x74] = &LD_derefHL_H;
    opcode_functions[0x75] = &LD_derefHL_L;
    opcode_functions[0x76] = &HALT;
    opcode_functions[0x77] = &LD_derefHL_A;
    opcode_functions[0x78] = &LD_A_B;
    opcode_functions[0x79] = &LD_A_C;
    opcode_functions[0x7A] = &LD_A_D;
    opcode_functions[0x7B] = &LD_A_E;
    opcode_functions[0x7C] = &LD_A_H;
    opcode_functions[0x7D] = &LD_A_L;
    opcode_functions[0x7E] = &LD_A_derefHL;
    opcode_functions[0x7F] = &LD_A_A;
    opcode_functions[0x80] = &ADD_A_B;
    opcode_functions[0x81] = &ADD_A_C;
    opcode_functions[0x82] = &ADD_A_D;
    opcode_functions[0x83] = &ADD_A_E;
    opcode_functions[0x84] = &ADD_A_H;
    opcode_functions[0x85] = &ADD_A_L;
    opcode_functions[0x86] = &ADD_A_derefHL;
    opcode_functions[0x87] = &ADD_A_A;
    opcode_functions[0x88] = &ADC_A_B;
    opcode_functions[0x89] = &ADC_A_C;
    opcode_functions[0x8A] = &ADC_A_D;
    opcode_functions[0x8B] = &ADC_A_E;
    opcode_functions[0x8C] = &ADC_A_H;
    opcode_functions[0x8D] = &ADC_A_L;
    opcode_functions[0x8E] = &ADC_A_derefHL;
    opcode_functions[0x8F] = &ADC_A_A;
    opcode_functions[0x90] = &SUB_B;
    opcode_functions[0x91] = &SUB_C;
    opcode_functions[0x92] = &SUB_D;
    opcode_functions[0x93] = &SUB_E;
    opcode_functions[0x94] = &SUB_H;
    opcode_functions[0x95] = &SUB_L;
    opcode_functions[0x96] = &SUB_derefHL;
    opcode_functions[0x97] = &SUB_A;
    opcode_functions[0x98] = &SBC_A_B;
    opcode_functions[0x99] = &SBC_A_C;
    opcode_functions[0x9A] = &SBC_A_D;
    opcode_functions[0x9B] = &SBC_A_E;
    opcode_functions[0x9C] = &SBC_A_H;
    opcode_functions[0x9D] = &SBC_A_L;
    opcode_functions[0x9E] = &SBC_A_derefHL;
    opcode_functions[0x9F] = &SBC_A_A;
    opcode_functions[0xA0] = &AND_B;
    opcode_functions[0xA1] = &AND_C;
    opcode_functions[0xA2] = &AND_D;
    opcode_functions[0xA3] = &AND_E;
    opcode_functions[0xA4] = &AND_H;
    opcode_functions[0xA5] = &AND_L;
    opcode_functions[0xA6] = &AND_derefHL;
    opcode_functions[0xA7] = &AND_A;
    opcode_functions[0xA8] = &XOR_B;
    opcode_functions[0xA9] = &XOR_C;
    opcode_functions[0xAA] = &XOR_D;
    opcode_functions[0xAB] = &XOR_E;
    opcode_functions[0xAC] = &XOR_H;
    opcode_functions[0xAD] = &XOR_L;
    opcode_functions[0xAE] = &XOR_derefHL;
    opcode_functions[0xAF] = &XOR_A;
    opcode_functions[0xB0] = &OR_B;
    opcode_functions[0xB1] = &OR_C;
    opcode_functions[0xB2] = &OR_D;
    opcode_functions[0xB3] = &OR_E;
    opcode_functions[0xB4] = &OR_H;
    opcode_functions[0xB5] = &OR_L;
    opcode_functions[0xB6] = &OR_derefHL;
    opcode_functions[0xB7] = &OR_A;
    opcode_functions[0xB8] = &CP_B;
    opcode_functions[0xB9] = &CP_C;
    opcode_functions[0xBA] = &CP_D;
    opcode_functions[0xBB] = &CP_E;
    opcode_functions[0xBC] = &CP_H;
    opcode_functions[0xBD] = &CP_L;
    opcode_functions[0xBE] = &CP_derefHL;
    opcode_functions[0xBF] = &CP_A;
    opcode_functions[0xC0] = &RET_NZ;
    opcode_functions[0xC1] = &POP_BC;
    opcode_functions[0xC2] = &JP_NZ_a16;
    opcode_functions[0xC3] = &JP_a16;
    opcode_functions[0xC4] = &CALL_NZ_a16;
    opcode_functions[0xC5] = &PUSH_BC;
    opcode_functions[0xC6] = &ADD_A_d8;
    opcode_functions[0xC7] = &RST_00H;
    opcode_functions[0xC8] = &RET_Z;
    opcode_functions[0xC9] = &RET;
    opcode_functions[0xCA] = &JP_Z_a16;
    opcode_functions[0xCB] = &PREFIX_CB;
    opcode_functions[0xCC] = &CALL_Z_a16;
    opcode_functions[0xCD] = &CALL_a16;
    opcode_functions[0xCE] = &ADC_A_d8;
    opcode_functions[0xCF] = &RST_08H;
    opcode_functions[0xD0] = &RET_NC;
    opcode_functions[0xD1] = &POP_DE;
    opcode_functions[0xD2] = &JP_NC_a16;
    opcode_functions[0xD3] = &opcode_non_existant;
    opcode_functions[0xD4] = &CALL_NC_a16;
    opcode_functions[0xD5] = &PUSH_DE;
    opcode_functions[0xD6] = &SUB_d8;
    opcode_functions[0xD7] = &RST_10H;
    opcode_functions[0xD8] = &RET_C;
    opcode_functions[0xD9] = &RETI;
    opcode_functions[0xDA] = &JP_C_a16;
    opcode_functions[0xDB] = &opcode_non_existant;
    opcode_functions[0xDC] = &CALL_C_a16;
    opcode_functions[0xDD] = &opcode_non_existant;
    opcode_functions[0xDE] = &SBC_A_d8;
    opcode_functions[0xDF] = &RST_18H;
    opcode_functions[0xE0] = &LDH_derefa8_A;
    opcode_functions[0xE1] = &POP_HL;
    opcode_functions[0xE2] = &LD_derefC_A;
    opcode_functions[0xE3] = &opcode_non_existant;
    opcode_functions[0xE4] = &opcode_non_existant;
    opcode_functions[0xE5] = &PUSH_HL;
    opcode_functions[0xE6] = &AND_d8;
    opcode_functions[0xE7] = &RST_20H;
    opcode_functions[0xE8] = &ADD_SP_r8;
    opcode_functions[0xE9] = &JP_derefHL;
    opcode_functions[0xEA] = &LD_derefa16_A;
    opcode_functions[0xEB] = &opcode_non_existant;
    opcode_functions[0xEC] = &opcode_non_existant;
    opcode_functions[0xED] = &opcode_non_existant;
    opcode_functions[0xEE] = &XOR_d8;
    opcode_functions[0xEF] = &RST_28H;
    opcode_functions[0xF0] = &LDH_A_derefa8;
    opcode_functions[0xF1] = &POP_AF;
    opcode_functions[0xF2] = &LD_A_derefC;
    opcode_functions[0xF3] = &DI;
    opcode_functions[0xF4] = &opcode_non_existant;
    opcode_functions[0xF5] = &PUSH_AF;
    opcode_functions[0xF6] = &OR_d8;
    opcode_functions[0xF7] = &RST_30H;
    opcode_functions[0xF8] = &LD_HL_SPplusr8;
    opcode_functions[0xF9] = &LD_SP_HL;
    opcode_functions[0xFA] = &LD_A_derefa16;
    opcode_functions[0xFB] = &EI;
    opcode_functions[0xFC] = &opcode_non_existant;
    opcode_functions[0xFD] = &opcode_non_existant;
    opcode_functions[0xFE] = &CP_d8;
    opcode_functions[0xFF] = &RST_38H;
}

void init_cb_pointers(void (*cb_functions[CB_NB]) (void*, uint8_t))
{
    cb_functions[0x00] = &prefixed_RLC_B;
    cb_functions[0x01] = &prefixed_RLC_C;
    cb_functions[0x02] = &prefixed_RLC_D;
    cb_functions[0x03] = &prefixed_RLC_E;
    cb_functions[0x04] = &prefixed_RLC_H;
    cb_functions[0x05] = &prefixed_RLC_L;
    cb_functions[0x06] = &prefixed_RLC_derefHL;
    cb_functions[0x07] = &prefixed_RLC_A;
    cb_functions[0x08] = &prefixed_RRC_B;
    cb_functions[0x09] = &prefixed_RRC_C;
    cb_functions[0x0A] = &prefixed_RRC_D;
    cb_functions[0x0B] = &prefixed_RRC_E;
    cb_functions[0x0C] = &prefixed_RRC_H;
    cb_functions[0x0D] = &prefixed_RRC_L;
    cb_functions[0x0E] = &prefixed_RRC_derefHL;
    cb_functions[0x0F] = &prefixed_RRC_A;
    cb_functions[0x10] = &prefixed_RL_B;
    cb_functions[0x11] = &prefixed_RL_C;
    cb_functions[0x12] = &prefixed_RL_D;
    cb_functions[0x13] = &prefixed_RL_E;
    cb_functions[0x14] = &prefixed_RL_H;
    cb_functions[0x15] = &prefixed_RL_L;
    cb_functions[0x16] = &prefixed_RL_derefHL;
    cb_functions[0x17] = &prefixed_RL_A;
    cb_functions[0x18] = &prefixed_RR_B;
    cb_functions[0x19] = &prefixed_RR_C;
    cb_functions[0x1A] = &prefixed_RR_D;
    cb_functions[0x1B] = &prefixed_RR_E;
    cb_functions[0x1C] = &prefixed_RR_H;
    cb_functions[0x1D] = &prefixed_RR_L;
    cb_functions[0x1E] = &prefixed_RR_derefHL;
    cb_functions[0x1F] = &prefixed_RR_A;
    cb_functions[0x20] = &prefixed_SLA_B;
    cb_functions[0x21] = &prefixed_SLA_C;
    cb_functions[0x22] = &prefixed_SLA_D;
    cb_functions[0x23] = &prefixed_SLA_E;
    cb_functions[0x24] = &prefixed_SLA_H;
    cb_functions[0x25] = &prefixed_SLA_L;
    cb_functions[0x26] = &prefixed_SLA_derefHL;
    cb_functions[0x27] = &prefixed_SLA_A;
    cb_functions[0x28] = &prefixed_SRA_B;
    cb_functions[0x29] = &prefixed_SRA_C;
    cb_functions[0x2A] = &prefixed_SRA_D;
    cb_functions[0x2B] = &prefixed_SRA_E;
    cb_functions[0x2C] = &prefixed_SRA_H;
    cb_functions[0x2D] = &prefixed_SRA_L;
    cb_functions[0x2E] = &prefixed_SRA_derefHL;
    cb_functions[0x2F] = &prefixed_SRA_A;
    cb_functions[0x30] = &prefixed_SWAP_B;
    cb_functions[0x31] = &prefixed_SWAP_C;
    cb_functions[0x32] = &prefixed_SWAP_D;
    cb_functions[0x33] = &prefixed_SWAP_E;
    cb_functions[0x34] = &prefixed_SWAP_H;
    cb_functions[0x35] = &prefixed_SWAP_L;
    cb_functions[0x36] = &prefixed_SWAP_derefHL;
    cb_functions[0x37] = &prefixed_SWAP_A;
    cb_functions[0x38] = &prefixed_SRL_B;
    cb_functions[0x39] = &prefixed_SRL_C;
    cb_functions[0x3A] = &prefixed_SRL_D;
    cb_functions[0x3B] = &prefixed_SRL_E;
    cb_functions[0x3C] = &prefixed_SRL_H;
    cb_functions[0x3D] = &prefixed_SRL_L;
    cb_functions[0x3E] = &prefixed_SRL_derefHL;
    cb_functions[0x3F] = &prefixed_SRL_A;
    cb_functions[0x40] = &prefixed_BIT_0_B;
    cb_functions[0x41] = &prefixed_BIT_0_C;
    cb_functions[0x42] = &prefixed_BIT_0_D;
    cb_functions[0x43] = &prefixed_BIT_0_E;
    cb_functions[0x44] = &prefixed_BIT_0_H;
    cb_functions[0x45] = &prefixed_BIT_0_L;
    cb_functions[0x46] = &prefixed_BIT_0_derefHL;
    cb_functions[0x47] = &prefixed_BIT_0_A;
    cb_functions[0x48] = &prefixed_BIT_1_B;
    cb_functions[0x49] = &prefixed_BIT_1_C;
    cb_functions[0x4A] = &prefixed_BIT_1_D;
    cb_functions[0x4B] = &prefixed_BIT_1_E;
    cb_functions[0x4C] = &prefixed_BIT_1_H;
    cb_functions[0x4D] = &prefixed_BIT_1_L;
    cb_functions[0x4E] = &prefixed_BIT_1_derefHL;
    cb_functions[0x4F] = &prefixed_BIT_1_A;
    cb_functions[0x50] = &prefixed_BIT_2_B;
    cb_functions[0x51] = &prefixed_BIT_2_C;
    cb_functions[0x52] = &prefixed_BIT_2_D;
    cb_functions[0x53] = &prefixed_BIT_2_E;
    cb_functions[0x54] = &prefixed_BIT_2_H;
    cb_functions[0x55] = &prefixed_BIT_2_L;
    cb_functions[0x56] = &prefixed_BIT_2_derefHL;
    cb_functions[0x57] = &prefixed_BIT_2_A;
    cb_functions[0x58] = &prefixed_BIT_3_B;
    cb_functions[0x59] = &prefixed_BIT_3_C;
    cb_functions[0x5A] = &prefixed_BIT_3_D;
    cb_functions[0x5B] = &prefixed_BIT_3_E;
    cb_functions[0x5C] = &prefixed_BIT_3_H;
    cb_functions[0x5D] = &prefixed_BIT_3_L;
    cb_functions[0x5E] = &prefixed_BIT_3_derefHL;
    cb_functions[0x5F] = &prefixed_BIT_3_A;
    cb_functions[0x60] = &prefixed_BIT_4_B;
    cb_functions[0x61] = &prefixed_BIT_4_C;
    cb_functions[0x62] = &prefixed_BIT_4_D;
    cb_functions[0x63] = &prefixed_BIT_4_E;
    cb_functions[0x64] = &prefixed_BIT_4_H;
    cb_functions[0x65] = &prefixed_BIT_4_L;
    cb_functions[0x66] = &prefixed_BIT_4_derefHL;
    cb_functions[0x67] = &prefixed_BIT_4_A;
    cb_functions[0x68] = &prefixed_BIT_5_B;
    cb_functions[0x69] = &prefixed_BIT_5_C;
    cb_functions[0x6A] = &prefixed_BIT_5_D;
    cb_functions[0x6B] = &prefixed_BIT_5_E;
    cb_functions[0x6C] = &prefixed_BIT_5_H;
    cb_functions[0x6D] = &prefixed_BIT_5_L;
    cb_functions[0x6E] = &prefixed_BIT_5_derefHL;
    cb_functions[0x6F] = &prefixed_BIT_5_A;
    cb_functions[0x70] = &prefixed_BIT_6_B;
    cb_functions[0x71] = &prefixed_BIT_6_C;
    cb_functions[0x72] = &prefixed_BIT_6_D;
    cb_functions[0x73] = &prefixed_BIT_6_E;
    cb_functions[0x74] = &prefixed_BIT_6_H;
    cb_functions[0x75] = &prefixed_BIT_6_L;
    cb_functions[0x76] = &prefixed_BIT_6_derefHL;
    cb_functions[0x77] = &prefixed_BIT_6_A;
    cb_functions[0x78] = &prefixed_BIT_7_B;
    cb_functions[0x79] = &prefixed_BIT_7_C;
    cb_functions[0x7A] = &prefixed_BIT_7_D;
    cb_functions[0x7B] = &prefixed_BIT_7_E;
    cb_functions[0x7C] = &prefixed_BIT_7_H;
    cb_functions[0x7D] = &prefixed_BIT_7_L;
    cb_functions[0x7E] = &prefixed_BIT_7_derefHL;
    cb_functions[0x7F] = &prefixed_BIT_7_A;
    cb_functions[0x80] = &prefixed_RES_0_B;
    cb_functions[0x81] = &prefixed_RES_0_C;
    cb_functions[0x82] = &prefixed_RES_0_D;
    cb_functions[0x83] = &prefixed_RES_0_E;
    cb_functions[0x84] = &prefixed_RES_0_H;
    cb_functions[0x85] = &prefixed_RES_0_L;
    cb_functions[0x86] = &prefixed_RES_0_derefHL;
    cb_functions[0x87] = &prefixed_RES_0_A;
    cb_functions[0x88] = &prefixed_RES_1_B;
    cb_functions[0x89] = &prefixed_RES_1_C;
    cb_functions[0x8A] = &prefixed_RES_1_D;
    cb_functions[0x8B] = &prefixed_RES_1_E;
    cb_functions[0x8C] = &prefixed_RES_1_H;
    cb_functions[0x8D] = &prefixed_RES_1_L;
    cb_functions[0x8E] = &prefixed_RES_1_derefHL;
    cb_functions[0x8F] = &prefixed_RES_1_A;
    cb_functions[0x90] = &prefixed_RES_2_B;
    cb_functions[0x91] = &prefixed_RES_2_C;
    cb_functions[0x92] = &prefixed_RES_2_D;
    cb_functions[0x93] = &prefixed_RES_2_E;
    cb_functions[0x94] = &prefixed_RES_2_H;
    cb_functions[0x95] = &prefixed_RES_2_L;
    cb_functions[0x96] = &prefixed_RES_2_derefHL;
    cb_functions[0x97] = &prefixed_RES_2_A;
    cb_functions[0x98] = &prefixed_RES_3_B;
    cb_functions[0x99] = &prefixed_RES_3_C;
    cb_functions[0x9A] = &prefixed_RES_3_D;
    cb_functions[0x9B] = &prefixed_RES_3_E;
    cb_functions[0x9C] = &prefixed_RES_3_H;
    cb_functions[0x9D] = &prefixed_RES_3_L;
    cb_functions[0x9E] = &prefixed_RES_3_derefHL;
    cb_functions[0x9F] = &prefixed_RES_3_A;
    cb_functions[0xA0] = &prefixed_RES_4_B;
    cb_functions[0xA1] = &prefixed_RES_4_C;
    cb_functions[0xA2] = &prefixed_RES_4_D;
    cb_functions[0xA3] = &prefixed_RES_4_E;
    cb_functions[0xA4] = &prefixed_RES_4_H;
    cb_functions[0xA5] = &prefixed_RES_4_L;
    cb_functions[0xA6] = &prefixed_RES_4_derefHL;
    cb_functions[0xA7] = &prefixed_RES_4_A;
    cb_functions[0xA8] = &prefixed_RES_5_B;
    cb_functions[0xA9] = &prefixed_RES_5_C;
    cb_functions[0xAA] = &prefixed_RES_5_D;
    cb_functions[0xAB] = &prefixed_RES_5_E;
    cb_functions[0xAC] = &prefixed_RES_5_H;
    cb_functions[0xAD] = &prefixed_RES_5_L;
    cb_functions[0xAE] = &prefixed_RES_5_derefHL;
    cb_functions[0xAF] = &prefixed_RES_5_A;
    cb_functions[0xB0] = &prefixed_RES_6_B;
    cb_functions[0xB1] = &prefixed_RES_6_C;
    cb_functions[0xB2] = &prefixed_RES_6_D;
    cb_functions[0xB3] = &prefixed_RES_6_E;
    cb_functions[0xB4] = &prefixed_RES_6_H;
    cb_functions[0xB5] = &prefixed_RES_6_L;
    cb_functions[0xB6] = &prefixed_RES_6_derefHL;
    cb_functions[0xB7] = &prefixed_RES_6_A;
    cb_functions[0xB8] = &prefixed_RES_7_B;
    cb_functions[0xB9] = &prefixed_RES_7_C;
    cb_functions[0xBA] = &prefixed_RES_7_D;
    cb_functions[0xBB] = &prefixed_RES_7_E;
    cb_functions[0xBC] = &prefixed_RES_7_H;
    cb_functions[0xBD] = &prefixed_RES_7_L;
    cb_functions[0xBE] = &prefixed_RES_7_derefHL;
    cb_functions[0xBF] = &prefixed_RES_7_A;
    cb_functions[0xC0] = &prefixed_SET_0_B;
    cb_functions[0xC1] = &prefixed_SET_0_C;
    cb_functions[0xC2] = &prefixed_SET_0_D;
    cb_functions[0xC3] = &prefixed_SET_0_E;
    cb_functions[0xC4] = &prefixed_SET_0_H;
    cb_functions[0xC5] = &prefixed_SET_0_L;
    cb_functions[0xC6] = &prefixed_SET_0_derefHL;
    cb_functions[0xC7] = &prefixed_SET_0_A;
    cb_functions[0xC8] = &prefixed_SET_1_B;
    cb_functions[0xC9] = &prefixed_SET_1_C;
    cb_functions[0xCA] = &prefixed_SET_1_D;
    cb_functions[0xCB] = &prefixed_SET_1_E;
    cb_functions[0xCC] = &prefixed_SET_1_H;
    cb_functions[0xCD] = &prefixed_SET_1_L;
    cb_functions[0xCE] = &prefixed_SET_1_derefHL;
    cb_functions[0xCF] = &prefixed_SET_1_A;
    cb_functions[0xD0] = &prefixed_SET_2_B;
    cb_functions[0xD1] = &prefixed_SET_2_C;
    cb_functions[0xD2] = &prefixed_SET_2_D;
    cb_functions[0xD3] = &prefixed_SET_2_E;
    cb_functions[0xD4] = &prefixed_SET_2_H;
    cb_functions[0xD5] = &prefixed_SET_2_L;
    cb_functions[0xD6] = &prefixed_SET_2_derefHL;
    cb_functions[0xD7] = &prefixed_SET_2_A;
    cb_functions[0xD8] = &prefixed_SET_3_B;
    cb_functions[0xD9] = &prefixed_SET_3_C;
    cb_functions[0xDA] = &prefixed_SET_3_D;
    cb_functions[0xDB] = &prefixed_SET_3_E;
    cb_functions[0xDC] = &prefixed_SET_3_H;
    cb_functions[0xDD] = &prefixed_SET_3_L;
    cb_functions[0xDE] = &prefixed_SET_3_derefHL;
    cb_functions[0xDF] = &prefixed_SET_3_A;
    cb_functions[0xE0] = &prefixed_SET_4_B;
    cb_functions[0xE1] = &prefixed_SET_4_C;
    cb_functions[0xE2] = &prefixed_SET_4_D;
    cb_functions[0xE3] = &prefixed_SET_4_E;
    cb_functions[0xE4] = &prefixed_SET_4_H;
    cb_functions[0xE5] = &prefixed_SET_4_L;
    cb_functions[0xE6] = &prefixed_SET_4_derefHL;
    cb_functions[0xE7] = &prefixed_SET_4_A;
    cb_functions[0xE8] = &prefixed_SET_5_B;
    cb_functions[0xE9] = &prefixed_SET_5_C;
    cb_functions[0xEA] = &prefixed_SET_5_D;
    cb_functions[0xEB] = &prefixed_SET_5_E;
    cb_functions[0xEC] = &prefixed_SET_5_H;
    cb_functions[0xED] = &prefixed_SET_5_L;
    cb_functions[0xEE] = &prefixed_SET_5_derefHL;
    cb_functions[0xEF] = &prefixed_SET_5_A;
    cb_functions[0xF0] = &prefixed_SET_6_B;
    cb_functions[0xF1] = &prefixed_SET_6_C;
    cb_functions[0xF2] = &prefixed_SET_6_D;
    cb_functions[0xF3] = &prefixed_SET_6_E;
    cb_functions[0xF4] = &prefixed_SET_6_H;
    cb_functions[0xF5] = &prefixed_SET_6_L;
    cb_functions[0xF6] = &prefixed_SET_6_derefHL;
    cb_functions[0xF7] = &prefixed_SET_6_A;
    cb_functions[0xF8] = &prefixed_SET_7_B;
    cb_functions[0xF9] = &prefixed_SET_7_C;
    cb_functions[0xFA] = &prefixed_SET_7_D;
    cb_functions[0xFB] = &prefixed_SET_7_E;
    cb_functions[0xFC] = &prefixed_SET_7_H;
    cb_functions[0xFD] = &prefixed_SET_7_L;
    cb_functions[0xFE] = &prefixed_SET_7_derefHL;
    cb_functions[0xFF] = &prefixed_SET_7_A;
}

void init_prefix_mnemonic_index(s_emu *emu)
{
    snprintf(emu->prefixed_mnemonic_index[0x00], 15, "RLC B");
    snprintf(emu->prefixed_mnemonic_index[0x01], 15, "RLC C");
    snprintf(emu->prefixed_mnemonic_index[0x02], 15, "RLC D");
    snprintf(emu->prefixed_mnemonic_index[0x03], 15, "RLC E");
    snprintf(emu->prefixed_mnemonic_index[0x04], 15, "RLC H");
    snprintf(emu->prefixed_mnemonic_index[0x05], 15, "RLC L");
    snprintf(emu->prefixed_mnemonic_index[0x06], 15, "RLC (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x07], 15, "RLC A");
    snprintf(emu->prefixed_mnemonic_index[0x08], 15, "RRC B");
    snprintf(emu->prefixed_mnemonic_index[0x09], 15, "RRC C");
    snprintf(emu->prefixed_mnemonic_index[0x0A], 15, "RRC D");
    snprintf(emu->prefixed_mnemonic_index[0x0B], 15, "RRC E");
    snprintf(emu->prefixed_mnemonic_index[0x0C], 15, "RRC H");
    snprintf(emu->prefixed_mnemonic_index[0x0D], 15, "RRC L");
    snprintf(emu->prefixed_mnemonic_index[0x0E], 15, "RRC (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x0F], 15, "RRC A");
    snprintf(emu->prefixed_mnemonic_index[0x10], 15, "RL B");
    snprintf(emu->prefixed_mnemonic_index[0x11], 15, "RL C");
    snprintf(emu->prefixed_mnemonic_index[0x12], 15, "RL D");
    snprintf(emu->prefixed_mnemonic_index[0x13], 15, "RL E");
    snprintf(emu->prefixed_mnemonic_index[0x14], 15, "RL H");
    snprintf(emu->prefixed_mnemonic_index[0x15], 15, "RL L");
    snprintf(emu->prefixed_mnemonic_index[0x16], 15, "RL (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x17], 15, "RL A");
    snprintf(emu->prefixed_mnemonic_index[0x18], 15, "RR B");
    snprintf(emu->prefixed_mnemonic_index[0x19], 15, "RR C");
    snprintf(emu->prefixed_mnemonic_index[0x1A], 15, "RR D");
    snprintf(emu->prefixed_mnemonic_index[0x1B], 15, "RR E");
    snprintf(emu->prefixed_mnemonic_index[0x1C], 15, "RR H");
    snprintf(emu->prefixed_mnemonic_index[0x1D], 15, "RR L");
    snprintf(emu->prefixed_mnemonic_index[0x1E], 15, "RR (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x1F], 15, "RR A");
    snprintf(emu->prefixed_mnemonic_index[0x20], 15, "SLA B");
    snprintf(emu->prefixed_mnemonic_index[0x21], 15, "SLA C");
    snprintf(emu->prefixed_mnemonic_index[0x22], 15, "SLA D");
    snprintf(emu->prefixed_mnemonic_index[0x23], 15, "SLA E");
    snprintf(emu->prefixed_mnemonic_index[0x24], 15, "SLA H");
    snprintf(emu->prefixed_mnemonic_index[0x25], 15, "SLA L");
    snprintf(emu->prefixed_mnemonic_index[0x26], 15, "SLA (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x27], 15, "SLA A");
    snprintf(emu->prefixed_mnemonic_index[0x28], 15, "SRA B");
    snprintf(emu->prefixed_mnemonic_index[0x29], 15, "SRA C");
    snprintf(emu->prefixed_mnemonic_index[0x2A], 15, "SRA D");
    snprintf(emu->prefixed_mnemonic_index[0x2B], 15, "SRA E");
    snprintf(emu->prefixed_mnemonic_index[0x2C], 15, "SRA H");
    snprintf(emu->prefixed_mnemonic_index[0x2D], 15, "SRA L");
    snprintf(emu->prefixed_mnemonic_index[0x2E], 15, "SRA (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x2F], 15, "SRA A");
    snprintf(emu->prefixed_mnemonic_index[0x30], 15, "SWAP B");
    snprintf(emu->prefixed_mnemonic_index[0x31], 15, "SWAP C");
    snprintf(emu->prefixed_mnemonic_index[0x32], 15, "SWAP D");
    snprintf(emu->prefixed_mnemonic_index[0x33], 15, "SWAP E");
    snprintf(emu->prefixed_mnemonic_index[0x34], 15, "SWAP H");
    snprintf(emu->prefixed_mnemonic_index[0x35], 15, "SWAP L");
    snprintf(emu->prefixed_mnemonic_index[0x36], 15, "SWAP (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x37], 15, "SWAP A");
    snprintf(emu->prefixed_mnemonic_index[0x38], 15, "SRL B");
    snprintf(emu->prefixed_mnemonic_index[0x39], 15, "SRL C");
    snprintf(emu->prefixed_mnemonic_index[0x3A], 15, "SRL D");
    snprintf(emu->prefixed_mnemonic_index[0x3B], 15, "SRL E");
    snprintf(emu->prefixed_mnemonic_index[0x3C], 15, "SRL H");
    snprintf(emu->prefixed_mnemonic_index[0x3D], 15, "SRL L");
    snprintf(emu->prefixed_mnemonic_index[0x3E], 15, "SRL (HL)");
    snprintf(emu->prefixed_mnemonic_index[0x3F], 15, "SRL A");
    snprintf(emu->prefixed_mnemonic_index[0x40], 15, "BIT 0,B");
    snprintf(emu->prefixed_mnemonic_index[0x41], 15, "BIT 0,C");
    snprintf(emu->prefixed_mnemonic_index[0x42], 15, "BIT 0,D");
    snprintf(emu->prefixed_mnemonic_index[0x43], 15, "BIT 0,E");
    snprintf(emu->prefixed_mnemonic_index[0x44], 15, "BIT 0,H");
    snprintf(emu->prefixed_mnemonic_index[0x45], 15, "BIT 0,L");
    snprintf(emu->prefixed_mnemonic_index[0x46], 15, "BIT 0,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x47], 15, "BIT 0,A");
    snprintf(emu->prefixed_mnemonic_index[0x48], 15, "BIT 1,B");
    snprintf(emu->prefixed_mnemonic_index[0x49], 15, "BIT 1,C");
    snprintf(emu->prefixed_mnemonic_index[0x4A], 15, "BIT 1,D");
    snprintf(emu->prefixed_mnemonic_index[0x4B], 15, "BIT 1,E");
    snprintf(emu->prefixed_mnemonic_index[0x4C], 15, "BIT 1,H");
    snprintf(emu->prefixed_mnemonic_index[0x4D], 15, "BIT 1,L");
    snprintf(emu->prefixed_mnemonic_index[0x4E], 15, "BIT 1,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x4F], 15, "BIT 1,A");
    snprintf(emu->prefixed_mnemonic_index[0x50], 15, "BIT 2,B");
    snprintf(emu->prefixed_mnemonic_index[0x51], 15, "BIT 2,C");
    snprintf(emu->prefixed_mnemonic_index[0x52], 15, "BIT 2,D");
    snprintf(emu->prefixed_mnemonic_index[0x53], 15, "BIT 2,E");
    snprintf(emu->prefixed_mnemonic_index[0x54], 15, "BIT 2,H");
    snprintf(emu->prefixed_mnemonic_index[0x55], 15, "BIT 2,L");
    snprintf(emu->prefixed_mnemonic_index[0x56], 15, "BIT 2,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x57], 15, "BIT 2,A");
    snprintf(emu->prefixed_mnemonic_index[0x58], 15, "BIT 3,B");
    snprintf(emu->prefixed_mnemonic_index[0x59], 15, "BIT 3,C");
    snprintf(emu->prefixed_mnemonic_index[0x5A], 15, "BIT 3,D");
    snprintf(emu->prefixed_mnemonic_index[0x5B], 15, "BIT 3,E");
    snprintf(emu->prefixed_mnemonic_index[0x5C], 15, "BIT 3,H");
    snprintf(emu->prefixed_mnemonic_index[0x5D], 15, "BIT 3,L");
    snprintf(emu->prefixed_mnemonic_index[0x5E], 15, "BIT 3,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x5F], 15, "BIT 3,A");
    snprintf(emu->prefixed_mnemonic_index[0x60], 15, "BIT 4,B");
    snprintf(emu->prefixed_mnemonic_index[0x61], 15, "BIT 4,C");
    snprintf(emu->prefixed_mnemonic_index[0x62], 15, "BIT 4,D");
    snprintf(emu->prefixed_mnemonic_index[0x63], 15, "BIT 4,E");
    snprintf(emu->prefixed_mnemonic_index[0x64], 15, "BIT 4,H");
    snprintf(emu->prefixed_mnemonic_index[0x65], 15, "BIT 4,L");
    snprintf(emu->prefixed_mnemonic_index[0x66], 15, "BIT 4,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x67], 15, "BIT 4,A");
    snprintf(emu->prefixed_mnemonic_index[0x68], 15, "BIT 5,B");
    snprintf(emu->prefixed_mnemonic_index[0x69], 15, "BIT 5,C");
    snprintf(emu->prefixed_mnemonic_index[0x6A], 15, "BIT 5,D");
    snprintf(emu->prefixed_mnemonic_index[0x6B], 15, "BIT 5,E");
    snprintf(emu->prefixed_mnemonic_index[0x6C], 15, "BIT 5,H");
    snprintf(emu->prefixed_mnemonic_index[0x6D], 15, "BIT 5,L");
    snprintf(emu->prefixed_mnemonic_index[0x6E], 15, "BIT 5,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x6F], 15, "BIT 5,A");
    snprintf(emu->prefixed_mnemonic_index[0x70], 15, "BIT 6,B");
    snprintf(emu->prefixed_mnemonic_index[0x71], 15, "BIT 6,C");
    snprintf(emu->prefixed_mnemonic_index[0x72], 15, "BIT 6,D");
    snprintf(emu->prefixed_mnemonic_index[0x73], 15, "BIT 6,E");
    snprintf(emu->prefixed_mnemonic_index[0x74], 15, "BIT 6,H");
    snprintf(emu->prefixed_mnemonic_index[0x75], 15, "BIT 6,L");
    snprintf(emu->prefixed_mnemonic_index[0x76], 15, "BIT 6,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x77], 15, "BIT 6,A");
    snprintf(emu->prefixed_mnemonic_index[0x78], 15, "BIT 7,B");
    snprintf(emu->prefixed_mnemonic_index[0x79], 15, "BIT 7,C");
    snprintf(emu->prefixed_mnemonic_index[0x7A], 15, "BIT 7,D");
    snprintf(emu->prefixed_mnemonic_index[0x7B], 15, "BIT 7,E");
    snprintf(emu->prefixed_mnemonic_index[0x7C], 15, "BIT 7,H");
    snprintf(emu->prefixed_mnemonic_index[0x7D], 15, "BIT 7,L");
    snprintf(emu->prefixed_mnemonic_index[0x7E], 15, "BIT 7,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x7F], 15, "BIT 7,A");
    snprintf(emu->prefixed_mnemonic_index[0x80], 15, "RES 0,B");
    snprintf(emu->prefixed_mnemonic_index[0x81], 15, "RES 0,C");
    snprintf(emu->prefixed_mnemonic_index[0x82], 15, "RES 0,D");
    snprintf(emu->prefixed_mnemonic_index[0x83], 15, "RES 0,E");
    snprintf(emu->prefixed_mnemonic_index[0x84], 15, "RES 0,H");
    snprintf(emu->prefixed_mnemonic_index[0x85], 15, "RES 0,L");
    snprintf(emu->prefixed_mnemonic_index[0x86], 15, "RES 0,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x87], 15, "RES 0,A");
    snprintf(emu->prefixed_mnemonic_index[0x88], 15, "RES 1,B");
    snprintf(emu->prefixed_mnemonic_index[0x89], 15, "RES 1,C");
    snprintf(emu->prefixed_mnemonic_index[0x8A], 15, "RES 1,D");
    snprintf(emu->prefixed_mnemonic_index[0x8B], 15, "RES 1,E");
    snprintf(emu->prefixed_mnemonic_index[0x8C], 15, "RES 1,H");
    snprintf(emu->prefixed_mnemonic_index[0x8D], 15, "RES 1,L");
    snprintf(emu->prefixed_mnemonic_index[0x8E], 15, "RES 1,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x8F], 15, "RES 1,A");
    snprintf(emu->prefixed_mnemonic_index[0x90], 15, "RES 2,B");
    snprintf(emu->prefixed_mnemonic_index[0x91], 15, "RES 2,C");
    snprintf(emu->prefixed_mnemonic_index[0x92], 15, "RES 2,D");
    snprintf(emu->prefixed_mnemonic_index[0x93], 15, "RES 2,E");
    snprintf(emu->prefixed_mnemonic_index[0x94], 15, "RES 2,H");
    snprintf(emu->prefixed_mnemonic_index[0x95], 15, "RES 2,L");
    snprintf(emu->prefixed_mnemonic_index[0x96], 15, "RES 2,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x97], 15, "RES 2,A");
    snprintf(emu->prefixed_mnemonic_index[0x98], 15, "RES 3,B");
    snprintf(emu->prefixed_mnemonic_index[0x99], 15, "RES 3,C");
    snprintf(emu->prefixed_mnemonic_index[0x9A], 15, "RES 3,D");
    snprintf(emu->prefixed_mnemonic_index[0x9B], 15, "RES 3,E");
    snprintf(emu->prefixed_mnemonic_index[0x9C], 15, "RES 3,H");
    snprintf(emu->prefixed_mnemonic_index[0x9D], 15, "RES 3,L");
    snprintf(emu->prefixed_mnemonic_index[0x9E], 15, "RES 3,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0x9F], 15, "RES 3,A");
    snprintf(emu->prefixed_mnemonic_index[0xA0], 15, "RES 4,B");
    snprintf(emu->prefixed_mnemonic_index[0xA1], 15, "RES 4,C");
    snprintf(emu->prefixed_mnemonic_index[0xA2], 15, "RES 4,D");
    snprintf(emu->prefixed_mnemonic_index[0xA3], 15, "RES 4,E");
    snprintf(emu->prefixed_mnemonic_index[0xA4], 15, "RES 4,H");
    snprintf(emu->prefixed_mnemonic_index[0xA5], 15, "RES 4,L");
    snprintf(emu->prefixed_mnemonic_index[0xA6], 15, "RES 4,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xA7], 15, "RES 4,A");
    snprintf(emu->prefixed_mnemonic_index[0xA8], 15, "RES 5,B");
    snprintf(emu->prefixed_mnemonic_index[0xA9], 15, "RES 5,C");
    snprintf(emu->prefixed_mnemonic_index[0xAA], 15, "RES 5,D");
    snprintf(emu->prefixed_mnemonic_index[0xAB], 15, "RES 5,E");
    snprintf(emu->prefixed_mnemonic_index[0xAC], 15, "RES 5,H");
    snprintf(emu->prefixed_mnemonic_index[0xAD], 15, "RES 5,L");
    snprintf(emu->prefixed_mnemonic_index[0xAE], 15, "RES 5,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xAF], 15, "RES 5,A");
    snprintf(emu->prefixed_mnemonic_index[0xB0], 15, "RES 6,B");
    snprintf(emu->prefixed_mnemonic_index[0xB1], 15, "RES 6,C");
    snprintf(emu->prefixed_mnemonic_index[0xB2], 15, "RES 6,D");
    snprintf(emu->prefixed_mnemonic_index[0xB3], 15, "RES 6,E");
    snprintf(emu->prefixed_mnemonic_index[0xB4], 15, "RES 6,H");
    snprintf(emu->prefixed_mnemonic_index[0xB5], 15, "RES 6,L");
    snprintf(emu->prefixed_mnemonic_index[0xB6], 15, "RES 6,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xB7], 15, "RES 6,A");
    snprintf(emu->prefixed_mnemonic_index[0xB8], 15, "RES 7,B");
    snprintf(emu->prefixed_mnemonic_index[0xB9], 15, "RES 7,C");
    snprintf(emu->prefixed_mnemonic_index[0xBA], 15, "RES 7,D");
    snprintf(emu->prefixed_mnemonic_index[0xBB], 15, "RES 7,E");
    snprintf(emu->prefixed_mnemonic_index[0xBC], 15, "RES 7,H");
    snprintf(emu->prefixed_mnemonic_index[0xBD], 15, "RES 7,L");
    snprintf(emu->prefixed_mnemonic_index[0xBE], 15, "RES 7,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xBF], 15, "RES 7,A");
    snprintf(emu->prefixed_mnemonic_index[0xC0], 15, "SET 0,B");
    snprintf(emu->prefixed_mnemonic_index[0xC1], 15, "SET 0,C");
    snprintf(emu->prefixed_mnemonic_index[0xC2], 15, "SET 0,D");
    snprintf(emu->prefixed_mnemonic_index[0xC3], 15, "SET 0,E");
    snprintf(emu->prefixed_mnemonic_index[0xC4], 15, "SET 0,H");
    snprintf(emu->prefixed_mnemonic_index[0xC5], 15, "SET 0,L");
    snprintf(emu->prefixed_mnemonic_index[0xC6], 15, "SET 0,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xC7], 15, "SET 0,A");
    snprintf(emu->prefixed_mnemonic_index[0xC8], 15, "SET 1,B");
    snprintf(emu->prefixed_mnemonic_index[0xC9], 15, "SET 1,C");
    snprintf(emu->prefixed_mnemonic_index[0xCA], 15, "SET 1,D");
    snprintf(emu->prefixed_mnemonic_index[0xCB], 15, "SET 1,E");
    snprintf(emu->prefixed_mnemonic_index[0xCC], 15, "SET 1,H");
    snprintf(emu->prefixed_mnemonic_index[0xCD], 15, "SET 1,L");
    snprintf(emu->prefixed_mnemonic_index[0xCE], 15, "SET 1,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xCF], 15, "SET 1,A");
    snprintf(emu->prefixed_mnemonic_index[0xD0], 15, "SET 2,B");
    snprintf(emu->prefixed_mnemonic_index[0xD1], 15, "SET 2,C");
    snprintf(emu->prefixed_mnemonic_index[0xD2], 15, "SET 2,D");
    snprintf(emu->prefixed_mnemonic_index[0xD3], 15, "SET 2,E");
    snprintf(emu->prefixed_mnemonic_index[0xD4], 15, "SET 2,H");
    snprintf(emu->prefixed_mnemonic_index[0xD5], 15, "SET 2,L");
    snprintf(emu->prefixed_mnemonic_index[0xD6], 15, "SET 2,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xD7], 15, "SET 2,A");
    snprintf(emu->prefixed_mnemonic_index[0xD8], 15, "SET 3,B");
    snprintf(emu->prefixed_mnemonic_index[0xD9], 15, "SET 3,C");
    snprintf(emu->prefixed_mnemonic_index[0xDA], 15, "SET 3,D");
    snprintf(emu->prefixed_mnemonic_index[0xDB], 15, "SET 3,E");
    snprintf(emu->prefixed_mnemonic_index[0xDC], 15, "SET 3,H");
    snprintf(emu->prefixed_mnemonic_index[0xDD], 15, "SET 3,L");
    snprintf(emu->prefixed_mnemonic_index[0xDE], 15, "SET 3,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xDF], 15, "SET 3,A");
    snprintf(emu->prefixed_mnemonic_index[0xE0], 15, "SET 4,B");
    snprintf(emu->prefixed_mnemonic_index[0xE1], 15, "SET 4,C");
    snprintf(emu->prefixed_mnemonic_index[0xE2], 15, "SET 4,D");
    snprintf(emu->prefixed_mnemonic_index[0xE3], 15, "SET 4,E");
    snprintf(emu->prefixed_mnemonic_index[0xE4], 15, "SET 4,H");
    snprintf(emu->prefixed_mnemonic_index[0xE5], 15, "SET 4,L");
    snprintf(emu->prefixed_mnemonic_index[0xE6], 15, "SET 4,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xE7], 15, "SET 4,A");
    snprintf(emu->prefixed_mnemonic_index[0xE8], 15, "SET 5,B");
    snprintf(emu->prefixed_mnemonic_index[0xE9], 15, "SET 5,C");
    snprintf(emu->prefixed_mnemonic_index[0xEA], 15, "SET 5,D");
    snprintf(emu->prefixed_mnemonic_index[0xEB], 15, "SET 5,E");
    snprintf(emu->prefixed_mnemonic_index[0xEC], 15, "SET 5,H");
    snprintf(emu->prefixed_mnemonic_index[0xED], 15, "SET 5,L");
    snprintf(emu->prefixed_mnemonic_index[0xEE], 15, "SET 5,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xEF], 15, "SET 5,A");
    snprintf(emu->prefixed_mnemonic_index[0xF0], 15, "SET 6,B");
    snprintf(emu->prefixed_mnemonic_index[0xF1], 15, "SET 6,C");
    snprintf(emu->prefixed_mnemonic_index[0xF2], 15, "SET 6,D");
    snprintf(emu->prefixed_mnemonic_index[0xF3], 15, "SET 6,E");
    snprintf(emu->prefixed_mnemonic_index[0xF4], 15, "SET 6,H");
    snprintf(emu->prefixed_mnemonic_index[0xF5], 15, "SET 6,L");
    snprintf(emu->prefixed_mnemonic_index[0xF6], 15, "SET 6,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xF7], 15, "SET 6,A");
    snprintf(emu->prefixed_mnemonic_index[0xF8], 15, "SET 7,B");
    snprintf(emu->prefixed_mnemonic_index[0xF9], 15, "SET 7,C");
    snprintf(emu->prefixed_mnemonic_index[0xFA], 15, "SET 7,D");
    snprintf(emu->prefixed_mnemonic_index[0xFB], 15, "SET 7,E");
    snprintf(emu->prefixed_mnemonic_index[0xFC], 15, "SET 7,H");
    snprintf(emu->prefixed_mnemonic_index[0xFD], 15, "SET 7,L");
    snprintf(emu->prefixed_mnemonic_index[0xFE], 15, "SET 7,(HL)");
    snprintf(emu->prefixed_mnemonic_index[0xFF], 15, "SET 7,A");
}

void init_mnemonic_index(s_emu *emu)
{
    snprintf(emu->mnemonic_index[0x00], 15, "NOP");
    snprintf(emu->mnemonic_index[0x01], 15, "LD BC,d16");
    snprintf(emu->mnemonic_index[0x02], 15, "LD (BC),A");
    snprintf(emu->mnemonic_index[0x03], 15, "INC BC");
    snprintf(emu->mnemonic_index[0x04], 15, "INC B");
    snprintf(emu->mnemonic_index[0x05], 15, "DEC B");
    snprintf(emu->mnemonic_index[0x06], 15, "LD B,d8");
    snprintf(emu->mnemonic_index[0x07], 15, "RLCA");
    snprintf(emu->mnemonic_index[0x08], 15, "LD (a16),SP");
    snprintf(emu->mnemonic_index[0x09], 15, "ADD HL,BC");
    snprintf(emu->mnemonic_index[0x0A], 15, "LD A,(BC)");
    snprintf(emu->mnemonic_index[0x0B], 15, "DEC BC");
    snprintf(emu->mnemonic_index[0x0C], 15, "INC C");
    snprintf(emu->mnemonic_index[0x0D], 15, "DEC C");
    snprintf(emu->mnemonic_index[0x0E], 15, "LD C,d8");
    snprintf(emu->mnemonic_index[0x0F], 15, "RRCA");
    snprintf(emu->mnemonic_index[0x10], 15, "STOP 0");
    snprintf(emu->mnemonic_index[0x11], 15, "LD DE,d16");
    snprintf(emu->mnemonic_index[0x12], 15, "LD (DE),A");
    snprintf(emu->mnemonic_index[0x13], 15, "INC DE");
    snprintf(emu->mnemonic_index[0x14], 15, "INC D");
    snprintf(emu->mnemonic_index[0x15], 15, "DEC D");
    snprintf(emu->mnemonic_index[0x16], 15, "LD D,d8");
    snprintf(emu->mnemonic_index[0x17], 15, "RLA");
    snprintf(emu->mnemonic_index[0x18], 15, "JR r8");
    snprintf(emu->mnemonic_index[0x19], 15, "ADD HL,DE");
    snprintf(emu->mnemonic_index[0x1A], 15, "LD A,(DE)");
    snprintf(emu->mnemonic_index[0x1B], 15, "DEC DE");
    snprintf(emu->mnemonic_index[0x1C], 15, "INC E");
    snprintf(emu->mnemonic_index[0x1D], 15, "DEC E");
    snprintf(emu->mnemonic_index[0x1E], 15, "LD E,d8");
    snprintf(emu->mnemonic_index[0x1F], 15, "RRA");
    snprintf(emu->mnemonic_index[0x20], 15, "JR NZ,r8");
    snprintf(emu->mnemonic_index[0x21], 15, "LD HL,d16");
    snprintf(emu->mnemonic_index[0x22], 15, "LD (HL+),A");
    snprintf(emu->mnemonic_index[0x23], 15, "INC HL");
    snprintf(emu->mnemonic_index[0x24], 15, "INC H");
    snprintf(emu->mnemonic_index[0x25], 15, "DEC H");
    snprintf(emu->mnemonic_index[0x26], 15, "LD H,d8");
    snprintf(emu->mnemonic_index[0x27], 15, "DAA");
    snprintf(emu->mnemonic_index[0x28], 15, "JR Z,r8");
    snprintf(emu->mnemonic_index[0x29], 15, "ADD HL,HL");
    snprintf(emu->mnemonic_index[0x2A], 15, "LD A,(HL+)");
    snprintf(emu->mnemonic_index[0x2B], 15, "DEC HL");
    snprintf(emu->mnemonic_index[0x2C], 15, "INC L");
    snprintf(emu->mnemonic_index[0x2D], 15, "DEC L");
    snprintf(emu->mnemonic_index[0x2E], 15, "LD L,d8");
    snprintf(emu->mnemonic_index[0x2F], 15, "CPL");
    snprintf(emu->mnemonic_index[0x30], 15, "JR NC,r8");
    snprintf(emu->mnemonic_index[0x31], 15, "LD SP,d16");
    snprintf(emu->mnemonic_index[0x32], 15, "LD (HL-),A");
    snprintf(emu->mnemonic_index[0x33], 15, "INC SP");
    snprintf(emu->mnemonic_index[0x34], 15, "INC (HL)");
    snprintf(emu->mnemonic_index[0x35], 15, "DEC (HL)");
    snprintf(emu->mnemonic_index[0x36], 15, "LD (HL),d8");
    snprintf(emu->mnemonic_index[0x37], 15, "SCF");
    snprintf(emu->mnemonic_index[0x38], 15, "JR C,r8");
    snprintf(emu->mnemonic_index[0x39], 15, "ADD HL,SP");
    snprintf(emu->mnemonic_index[0x3A], 15, "LD A,(HL-)");
    snprintf(emu->mnemonic_index[0x3B], 15, "DEC SP");
    snprintf(emu->mnemonic_index[0x3C], 15, "INC A");
    snprintf(emu->mnemonic_index[0x3D], 15, "DEC A");
    snprintf(emu->mnemonic_index[0x3E], 15, "LD A,d8");
    snprintf(emu->mnemonic_index[0x3F], 15, "CCF");
    snprintf(emu->mnemonic_index[0x40], 15, "LD B,B");
    snprintf(emu->mnemonic_index[0x41], 15, "LD B,C");
    snprintf(emu->mnemonic_index[0x42], 15, "LD B,D");
    snprintf(emu->mnemonic_index[0x43], 15, "LD B,E");
    snprintf(emu->mnemonic_index[0x44], 15, "LD B,H");
    snprintf(emu->mnemonic_index[0x45], 15, "LD B,L");
    snprintf(emu->mnemonic_index[0x46], 15, "LD B,(HL)");
    snprintf(emu->mnemonic_index[0x47], 15, "LD B,A");
    snprintf(emu->mnemonic_index[0x48], 15, "LD C,B");
    snprintf(emu->mnemonic_index[0x49], 15, "LD C,C");
    snprintf(emu->mnemonic_index[0x4A], 15, "LD C,D");
    snprintf(emu->mnemonic_index[0x4B], 15, "LD C,E");
    snprintf(emu->mnemonic_index[0x4C], 15, "LD C,H");
    snprintf(emu->mnemonic_index[0x4D], 15, "LD C,L");
    snprintf(emu->mnemonic_index[0x4E], 15, "LD C,(HL)");
    snprintf(emu->mnemonic_index[0x4F], 15, "LD C,A");
    snprintf(emu->mnemonic_index[0x50], 15, "LD D,B");
    snprintf(emu->mnemonic_index[0x51], 15, "LD D,C");
    snprintf(emu->mnemonic_index[0x52], 15, "LD D,D");
    snprintf(emu->mnemonic_index[0x53], 15, "LD D,E");
    snprintf(emu->mnemonic_index[0x54], 15, "LD D,H");
    snprintf(emu->mnemonic_index[0x55], 15, "LD D,L");
    snprintf(emu->mnemonic_index[0x56], 15, "LD D,(HL)");
    snprintf(emu->mnemonic_index[0x57], 15, "LD D,A");
    snprintf(emu->mnemonic_index[0x58], 15, "LD E,B");
    snprintf(emu->mnemonic_index[0x59], 15, "LD E,C");
    snprintf(emu->mnemonic_index[0x5A], 15, "LD E,D");
    snprintf(emu->mnemonic_index[0x5B], 15, "LD E,E");
    snprintf(emu->mnemonic_index[0x5C], 15, "LD E,H");
    snprintf(emu->mnemonic_index[0x5D], 15, "LD E,L");
    snprintf(emu->mnemonic_index[0x5E], 15, "LD E,(HL)");
    snprintf(emu->mnemonic_index[0x5F], 15, "LD E,A");
    snprintf(emu->mnemonic_index[0x60], 15, "LD H,B");
    snprintf(emu->mnemonic_index[0x61], 15, "LD H,C");
    snprintf(emu->mnemonic_index[0x62], 15, "LD H,D");
    snprintf(emu->mnemonic_index[0x63], 15, "LD H,E");
    snprintf(emu->mnemonic_index[0x64], 15, "LD H,H");
    snprintf(emu->mnemonic_index[0x65], 15, "LD H,L");
    snprintf(emu->mnemonic_index[0x66], 15, "LD H,(HL)");
    snprintf(emu->mnemonic_index[0x67], 15, "LD H,A");
    snprintf(emu->mnemonic_index[0x68], 15, "LD L,B");
    snprintf(emu->mnemonic_index[0x69], 15, "LD L,C");
    snprintf(emu->mnemonic_index[0x6A], 15, "LD L,D");
    snprintf(emu->mnemonic_index[0x6B], 15, "LD L,E");
    snprintf(emu->mnemonic_index[0x6C], 15, "LD L,H");
    snprintf(emu->mnemonic_index[0x6D], 15, "LD L,L");
    snprintf(emu->mnemonic_index[0x6E], 15, "LD L,(HL)");
    snprintf(emu->mnemonic_index[0x6F], 15, "LD L,A");
    snprintf(emu->mnemonic_index[0x70], 15, "LD (HL),B");
    snprintf(emu->mnemonic_index[0x71], 15, "LD (HL),C");
    snprintf(emu->mnemonic_index[0x72], 15, "LD (HL),D");
    snprintf(emu->mnemonic_index[0x73], 15, "LD (HL),E");
    snprintf(emu->mnemonic_index[0x74], 15, "LD (HL),H");
    snprintf(emu->mnemonic_index[0x75], 15, "LD (HL),L");
    snprintf(emu->mnemonic_index[0x76], 15, "HALT");
    snprintf(emu->mnemonic_index[0x77], 15, "LD (HL),A");
    snprintf(emu->mnemonic_index[0x78], 15, "LD A,B");
    snprintf(emu->mnemonic_index[0x79], 15, "LD A,C");
    snprintf(emu->mnemonic_index[0x7A], 15, "LD A,D");
    snprintf(emu->mnemonic_index[0x7B], 15, "LD A,E");
    snprintf(emu->mnemonic_index[0x7C], 15, "LD A,H");
    snprintf(emu->mnemonic_index[0x7D], 15, "LD A,L");
    snprintf(emu->mnemonic_index[0x7E], 15, "LD A,(HL)");
    snprintf(emu->mnemonic_index[0x7F], 15, "LD A,A");
    snprintf(emu->mnemonic_index[0x80], 15, "ADD A,B");
    snprintf(emu->mnemonic_index[0x81], 15, "ADD A,C");
    snprintf(emu->mnemonic_index[0x82], 15, "ADD A,D");
    snprintf(emu->mnemonic_index[0x83], 15, "ADD A,E");
    snprintf(emu->mnemonic_index[0x84], 15, "ADD A,H");
    snprintf(emu->mnemonic_index[0x85], 15, "ADD A,L");
    snprintf(emu->mnemonic_index[0x86], 15, "ADD A,(HL)");
    snprintf(emu->mnemonic_index[0x87], 15, "ADD A,A");
    snprintf(emu->mnemonic_index[0x88], 15, "ADC A,B");
    snprintf(emu->mnemonic_index[0x89], 15, "ADC A,C");
    snprintf(emu->mnemonic_index[0x8A], 15, "ADC A,D");
    snprintf(emu->mnemonic_index[0x8B], 15, "ADC A,E");
    snprintf(emu->mnemonic_index[0x8C], 15, "ADC A,H");
    snprintf(emu->mnemonic_index[0x8D], 15, "ADC A,L");
    snprintf(emu->mnemonic_index[0x8E], 15, "ADC A,(HL)");
    snprintf(emu->mnemonic_index[0x8F], 15, "ADC A,A");
    snprintf(emu->mnemonic_index[0x90], 15, "SUB B");
    snprintf(emu->mnemonic_index[0x91], 15, "SUB C");
    snprintf(emu->mnemonic_index[0x92], 15, "SUB D");
    snprintf(emu->mnemonic_index[0x93], 15, "SUB E");
    snprintf(emu->mnemonic_index[0x94], 15, "SUB H");
    snprintf(emu->mnemonic_index[0x95], 15, "SUB L");
    snprintf(emu->mnemonic_index[0x96], 15, "SUB (HL)");
    snprintf(emu->mnemonic_index[0x97], 15, "SUB A");
    snprintf(emu->mnemonic_index[0x98], 15, "SBC A,B");
    snprintf(emu->mnemonic_index[0x99], 15, "SBC A,C");
    snprintf(emu->mnemonic_index[0x9A], 15, "SBC A,D");
    snprintf(emu->mnemonic_index[0x9B], 15, "SBC A,E");
    snprintf(emu->mnemonic_index[0x9C], 15, "SBC A,H");
    snprintf(emu->mnemonic_index[0x9D], 15, "SBC A,L");
    snprintf(emu->mnemonic_index[0x9E], 15, "SBC A,(HL)");
    snprintf(emu->mnemonic_index[0x9F], 15, "SBC A,A");
    snprintf(emu->mnemonic_index[0xA0], 15, "AND B");
    snprintf(emu->mnemonic_index[0xA1], 15, "AND C");
    snprintf(emu->mnemonic_index[0xA2], 15, "AND D");
    snprintf(emu->mnemonic_index[0xA3], 15, "AND E");
    snprintf(emu->mnemonic_index[0xA4], 15, "AND H");
    snprintf(emu->mnemonic_index[0xA5], 15, "AND L");
    snprintf(emu->mnemonic_index[0xA6], 15, "AND (HL)");
    snprintf(emu->mnemonic_index[0xA7], 15, "AND A");
    snprintf(emu->mnemonic_index[0xA8], 15, "XOR B");
    snprintf(emu->mnemonic_index[0xA9], 15, "XOR C");
    snprintf(emu->mnemonic_index[0xAA], 15, "XOR D");
    snprintf(emu->mnemonic_index[0xAB], 15, "XOR E");
    snprintf(emu->mnemonic_index[0xAC], 15, "XOR H");
    snprintf(emu->mnemonic_index[0xAD], 15, "XOR L");
    snprintf(emu->mnemonic_index[0xAE], 15, "XOR (HL)");
    snprintf(emu->mnemonic_index[0xAF], 15, "XOR A");
    snprintf(emu->mnemonic_index[0xB0], 15, "OR B");
    snprintf(emu->mnemonic_index[0xB1], 15, "OR C");
    snprintf(emu->mnemonic_index[0xB2], 15, "OR D");
    snprintf(emu->mnemonic_index[0xB3], 15, "OR E");
    snprintf(emu->mnemonic_index[0xB4], 15, "OR H");
    snprintf(emu->mnemonic_index[0xB5], 15, "OR L");
    snprintf(emu->mnemonic_index[0xB6], 15, "OR (HL)");
    snprintf(emu->mnemonic_index[0xB7], 15, "OR A");
    snprintf(emu->mnemonic_index[0xB8], 15, "CP B");
    snprintf(emu->mnemonic_index[0xB9], 15, "CP C");
    snprintf(emu->mnemonic_index[0xBA], 15, "CP D");
    snprintf(emu->mnemonic_index[0xBB], 15, "CP E");
    snprintf(emu->mnemonic_index[0xBC], 15, "CP H");
    snprintf(emu->mnemonic_index[0xBD], 15, "CP L");
    snprintf(emu->mnemonic_index[0xBE], 15, "CP (HL)");
    snprintf(emu->mnemonic_index[0xBF], 15, "CP A");
    snprintf(emu->mnemonic_index[0xC0], 15, "RET NZ");
    snprintf(emu->mnemonic_index[0xC1], 15, "POP BC");
    snprintf(emu->mnemonic_index[0xC2], 15, "JP NZ,a16");
    snprintf(emu->mnemonic_index[0xC3], 15, "JP a16");
    snprintf(emu->mnemonic_index[0xC4], 15, "CALL NZ,a16");
    snprintf(emu->mnemonic_index[0xC5], 15, "PUSH BC");
    snprintf(emu->mnemonic_index[0xC6], 15, "ADD A,d8");
    snprintf(emu->mnemonic_index[0xC7], 15, "RST 00H");
    snprintf(emu->mnemonic_index[0xC8], 15, "RET Z");
    snprintf(emu->mnemonic_index[0xC9], 15, "RET");
    snprintf(emu->mnemonic_index[0xCA], 15, "JP Z,a16");
    snprintf(emu->mnemonic_index[0xCB], 15, "PREFIX CB");
    snprintf(emu->mnemonic_index[0xCC], 15, "CALL Z,a16");
    snprintf(emu->mnemonic_index[0xCD], 15, "CALL a16");
    snprintf(emu->mnemonic_index[0xCE], 15, "ADC A,d8");
    snprintf(emu->mnemonic_index[0xCF], 15, "RST 08H");
    snprintf(emu->mnemonic_index[0xD0], 15, "RET NC");
    snprintf(emu->mnemonic_index[0xD1], 15, "POP DE");
    snprintf(emu->mnemonic_index[0xD2], 15, "JP NC,a16");
    snprintf(emu->mnemonic_index[0xD3], 15, " ");
    snprintf(emu->mnemonic_index[0xD4], 15, "CALL NC,a16");
    snprintf(emu->mnemonic_index[0xD5], 15, "PUSH DE");
    snprintf(emu->mnemonic_index[0xD6], 15, "SUB d8");
    snprintf(emu->mnemonic_index[0xD7], 15, "RST 10H");
    snprintf(emu->mnemonic_index[0xD8], 15, "RET C");
    snprintf(emu->mnemonic_index[0xD9], 15, "RETI");
    snprintf(emu->mnemonic_index[0xDA], 15, "JP C,a16");
    snprintf(emu->mnemonic_index[0xDB], 15, " ");
    snprintf(emu->mnemonic_index[0xDC], 15, "CALL C,a16");
    snprintf(emu->mnemonic_index[0xDD], 15, " ");
    snprintf(emu->mnemonic_index[0xDE], 15, "SBC A,d8");
    snprintf(emu->mnemonic_index[0xDF], 15, "RST 18H");
    snprintf(emu->mnemonic_index[0xE0], 15, "LDH (a8),A");
    snprintf(emu->mnemonic_index[0xE1], 15, "POP HL");
    snprintf(emu->mnemonic_index[0xE2], 15, "LD (C),A");
    snprintf(emu->mnemonic_index[0xE3], 15, " ");
    snprintf(emu->mnemonic_index[0xE4], 15, " ");
    snprintf(emu->mnemonic_index[0xE5], 15, "PUSH HL");
    snprintf(emu->mnemonic_index[0xE6], 15, "AND d8");
    snprintf(emu->mnemonic_index[0xE7], 15, "RST 20H");
    snprintf(emu->mnemonic_index[0xE8], 15, "ADD SP,r8");
    snprintf(emu->mnemonic_index[0xE9], 15, "JP (HL)");
    snprintf(emu->mnemonic_index[0xEA], 15, "LD (a16),A");
    snprintf(emu->mnemonic_index[0xEB], 15, " ");
    snprintf(emu->mnemonic_index[0xEC], 15, " ");
    snprintf(emu->mnemonic_index[0xED], 15, " ");
    snprintf(emu->mnemonic_index[0xEE], 15, "XOR d8");
    snprintf(emu->mnemonic_index[0xEF], 15, "RST 28H");
    snprintf(emu->mnemonic_index[0xF0], 15, "LDH A,(a8)");
    snprintf(emu->mnemonic_index[0xF1], 15, "POP AF");
    snprintf(emu->mnemonic_index[0xF2], 15, "LD A,(C)");
    snprintf(emu->mnemonic_index[0xF3], 15, "DI");
    snprintf(emu->mnemonic_index[0xF4], 15, " ");
    snprintf(emu->mnemonic_index[0xF5], 15, "PUSH AF");
    snprintf(emu->mnemonic_index[0xF6], 15, "OR d8");
    snprintf(emu->mnemonic_index[0xF7], 15, "RST 30H");
    snprintf(emu->mnemonic_index[0xF8], 15, "LD HL,SP+r8");
    snprintf(emu->mnemonic_index[0xF9], 15, "LD SP,HL");
    snprintf(emu->mnemonic_index[0xFA], 15, "LD A,(a16)");
    snprintf(emu->mnemonic_index[0xFB], 15, "EI");
    snprintf(emu->mnemonic_index[0xFC], 15, " ");
    snprintf(emu->mnemonic_index[0xFD], 15, " ");
    snprintf(emu->mnemonic_index[0xFE], 15, "CP d8");
    snprintf(emu->mnemonic_index[0xFF], 15, "RST 38H");
}

